### ISSUE TITLE
IMOS Feature Request: Tracking sensors serial numbers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aodn/imos-toolbox#110]
```
Sensors serial number can be documented for multi-sensor instruments in the 
deployment database. This information could then be reused to document NetCDF 
variables metadata each time necessary.
```

Original issue reported on code.google.com by `guillaum...@gmail.com` on 20 Sep 2011 at 5:19

**Comment by ggalibert** [comment]
Fixed in 51808463ead850271782bca8d02d57c1664ad24b, implementation was only possible thanks to the new schema from AIMS database : OceanDB2015. There are now critical information like start_date_config and end_date_config that can help to infer which was the relevant config at any time in the past.
