### ISSUE TITLE
Modify RDI ADCP parser

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aodn/imos-toolbox#146]
```
Being able to take into account old instruments that use to record pressure in 
absolute value (that is to say including atmosphere).
```

Original issue reported on code.google.com by `guillaum...@gmail.com` on 31 May 2012 at 7:59

**Comment by ggalibert** [comment]
> Being able to take into account old instruments that use to record pressure in 
> absolute value (that is to say including atmosphere).

@TimAus-NSW do you remember any RDI dataset that would be relevant to this case? I had this feedback from Brad a long time ago and I wonder this is still valid or not.

**Comment by TimAus-NSW** [comment]
Not that i am aware of. We had a number of files where the ADCP had been deployed in a depth greater than the pressure gauge was rated for (65m/50m). We were able to substitute the incorrect depths with depths from a pressure logger deployed with the instrument. 

I also believe there was a batch of pressure loggers that came back from CSIRO or Aquatec with their pressure sensors set at zero. I'm not sure how these were dealt with.
