### ISSUE TITLE
IMOS Feature Request: Add a "PARAM"_ADJUST variable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aodn/imos-toolbox#160]
```
A "PARAM"_ADJUST variable could contain only the values that are not flagged as 
bad (<=2). When bad we would have a FillValue.
```

Original issue reported on code.google.com by `guillaum...@gmail.com` on 4 Sep 2012 at 12:46

**Comment by ggalibert** [comment]
We've been going a different path. "PARAM" stays "PARAM", in FV00 it contains the original values while in FV01 and higher it can potentially contain modified values with comments.

**Comment by ggalibert** [comment]
Users need to look at the flags. In the future we might develop more the access to FV01 products that only include "good" data.
