### ISSUE TITLE
Manually QC a particular variable for all sensors

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aodn/imos-toolbox#185]
```
Currently in Time Series view, all variables for one instruments are displayed. 
Would also like to have a logical instrument eg {temperature} which would then 
display all temperature variables from all sensors being processed.
```

Original issue reported on code.google.com by `s.spag...@gmail.com` on 26 Nov 2013 at 2:49

**Comment by ggalibert** [comment]
This is the kind of situation such a feature would be useful:
![gbrhis-1103_temp_qc](https://cloud.githubusercontent.com/assets/3498686/12805586/c905eec6-cb50-11e5-886f-d996f94af330.png)

**Comment by ggalibert** [comment]
We could add an "All" entry in the top left combo box of the main window.
When selected, all distinct parameters collected on the mooring would be listed in the left set of tickboxes. Then, selected parameters of all instruments would be displayed on the same graph.

**Comment by ggalibert** [comment]
Planning to do the following:
![screenshot from 2017-07-19 17-29-00](https://user-images.githubusercontent.com/3498686/28452272-45daf21a-6e35-11e7-9df4-d514673b5536.png)
Optionally, the user can choose to plot an extra instrument in black. No need to plot all of the instruments to be able to do some cross validation. At least for now.

**Comment by ggalibert** [comment]
This has been implemented via commit https://github.com/aodn/imos-toolbox/commit/1d6fbdc4f977d548453179b0dd1ff3bd1fb20f7f in v2.5.31
