### ISSUE TITLE
IMOS Feature Request : How do we deal with clock offset?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aodn/imos-toolbox#198]
```
Do IMOS technicians measure time clock offset/drift? If so is it documented in 
the ddb? It should probably be the case...
```

Original issue reported on code.google.com by `guillaum...@gmail.com` on 27 May 2014 at 6:18

**Comment by ggalibert** [comment]
In the deployment database, for timeseries in the table DeploymentData one can use the field TimeDriftInstrument to record the clock drift when an instrument is retrieved.

We need to implement a PP routine to apply a linear correction for clock drift though.

**Comment by ggalibert** [comment]
timeDriftPP routine has been implemented.
