### ISSUE TITLE
IMOS Feature Request: Toolbox could be a checker

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aodn/imos-toolbox#240]
```
Toolbox could error/warn about missing compulsory/recommended metadata when 
outputting a NetCDF.
```

Original issue reported on code.google.com by `guillaum...@gmail.com` on 26 Nov 2014 at 6:13

**Comment by ggalibert** [comment]
The toolbox is already complicated enough. There is a dedicated checker software for that.
