### ISSUE TITLE
improve depthPP

### ISSUE THREAD

**Issue by ggalibert** [aodn/imos-toolbox#249]
When 2 nearest P sensors are used to infer depth of a third one, if one of the two fails at some stage, the third should still have DEPTH data inferred from the remaining one.

**Comment by sspagnol** [comment]
Have a case where from depthPP some values are created that will cause salinityPP to fail over. Can we add something like

computedDepth(computedDepth < 5) = NaN;

to depthPP.m at around line 560 (before the data is added to sample structure). Value 5 chosen as that is the cutoff in gsw_p_from_z that causes the issue.

**Comment by sspagnol** [comment]
And to follow on - in gsw_p_from_z the z is depth negative so think the line in depthPP should be

computedDepth(computedDepth < -5) = NaN;

**Comment by ggalibert** [comment]
@sspagnol this is not the right place to report a new issue.

**Comment by ggalibert** [comment]
Too difficult and probably not a good approach since the inferred depth would then have a jump between the moment it's inferred from 2 sensors to the moment it's only inferred from one. At this stage it is up to the user to spot any failing instrument so that they are not being used at all in depthPP.
