### ISSUE TITLE
Geomag limited to 93 characters for input paths

### ISSUE THREAD

**Issue by ggalibert** [aodn/imos-toolbox#252]
Working with full path can be problematic if the toolbox is living in a directory far from the root of the drive. This will create paths to input files longer than 93 characters.

Either see if we can use relative paths or document this problem somewhere on the wiki (install + magDecPP).

**Comment by petejan** [comment]
Fixed by re-compiling geomag70 and increasing path length

**Comment by ggalibert** [comment]
Fixed by https://github.com/aodn/imos-toolbox/commit/d1279d3b42e071dad165d2ffa9a2bf1b38ff0389
