### ISSUE TITLE
Keep RDI ADCP echo intensity (in counts) in netcdf file

### ISSUE THREAD

**Issue by sspagnol** [aodn/imos-toolbox#279]
Request from user that the original echo intensity in counts (RSSI) from RDI ADCP remain in the FV00/FV01 netcdf file.

The conversion to ABSI via 0.45 factor is a very rough approximation. More correct methods outlined in Gostiaux, L., van Haren, H., 2010. Extracting meaningful information from uncalibrated backscattered echo intensity data. Journal of Atmospheric and Oceanic Technology 27, 943–949 (update to procedure outlined in Deines, K. L., 1999: Backscatter estimation using broadband acoustic Doppler current profilers. Proc. Sixth Working Conf on Current Measurement, San Diego, CA, IEEE, 249–253).

The conversion factors *are* instrument dependent so they would prefer to have the original echo intensity value and run through the steps outlined in the paper. While you could implement eq 5 in Gostiaux paper you would still be assuming a *kc* and *Enoise*, and as highlighted in the paper

>The precise determination of kc is crucial if any quantitative measurement is to be done, because
> fluctuations of 20% are observed around the commonly used value of kc=0.45 (Deines 1999) and 
> also between the individual transducers of a single ADCP.

If you keep the 0.45 conversion to backscatter variable would also need to add to variable comment that this was calculated using the nominal conversion factor and as such the data is of undetermined quality.

Probably also means that echo intensity variable shouldn't be binned mapped (left as DIST_ALONG_BEAM), commented as such, and left to the user to handle.

**Comment by ggalibert** [comment]
Would that be OK to leave echo intensity in counts with 2nd dimension DIST_ALONG_BEAM in the FV00 file while we could suggest a value in dB with 2nd dimension being potentially HEIGHT_ABOVE_SENSOR in the FV01 file?

Could try to implement Gostiaux eq. 5 rather than simple factor, however we still need to choose *kc* and *Enoise* values like you highlighted. I understand these two values may be inferred from the dataset:

> The term *Enoise* is the tail value of the minimum RSSI profile over the total record.

> Scale factor *kc* and constant *A* are adjusted to obtain the best fit of (9) with the data, with *kc* being constrained to the range [0.35, 0.55].

Definitely agree that 0.45dB/count or any *kc* coefficient and methodology applied should be documented in the relevant variable attribute.

**Comment by sspagnol** [comment]
Agree, I think the FV00 should have the echo intensity (in DIST_ALONG_BEAMS). The nice part of it being in FV01 is that the in/out water times would be flagged. Have to see if other people will put forward their case for it to go into FV01. It might also mean that the ADC channels also have to go into the FV00, trying to get some info from RDI if these can be used for calculating transmit power etc which if people are really interested in getting as much info out of the RDI then they will need.

Have also asked RDI for the Kc values for our RDI to see the spread of values.

Do wonder that if you have to do some sort of minimization problem to calculate Idb==acoustic_backscatter_intensity (even with starting values from Deines 1999) then maybe thats going too far. And does all this discussion pertain to Norteks?

Might want to add to wiki that ABSI acoustic_backscatter_intensity is *not* (mean) volume_backscatter_strength (Sv calculated in Deines 1999, Gostiaux and van Haren 2010 [10log(sv)], Sassi and Hoitink and Vermeulen 2012 [includes near field correction]), have had one person ask if they where.

Really need an acoustics expert.

**Comment by ggalibert** [comment]
Simon, a first set of modifications to respond to some of the issues raised in this ticket : https://github.com/aodn/imos-toolbox/pull/298 Thanks for giving me any feedback.
