### ISSUE TITLE
now_utc warning on Win64 R2015b

### ISSUE THREAD

**Issue by sspagnol** [aodn/imos-toolbox#302]
On Win7 x86_64 R2015b Matlab now_utc gives me the following warning

Warning: A value of class "sun.util.calendar.ZoneInfo" was indexed with no subscripts specified.
Currently the result of this operation is the indexed value itself, but in a future release, 
it will be an error. 

I do not get the same warning under Linux R2015b.

Simple solution in now_utc.m is

nowt = java.lang.System.currentTimeMillis() / 86400000 + datenum([1970 1 1]);

Just registering issue in case it really is an issue with windows Matlab (and hopefully not just my machine).

Simon.

**Comment by ggalibert** [comment]
Fixed in https://github.com/aodn/imos-toolbox/commit/c18377afd857797fe72a2051f5be1ba3f85d0c71
