### ISSUE TITLE
error in running imostoolbox .bat file

### ISSUE THREAD

**Issue by phanindra1** [aodn/imos-toolbox#317]
HI

After following the procedure that was given in guidelines(bit confused at Deployment Database), I tried running imosToolbox.bat file. And I end up with this lines in command line window

"Processing field trip  from folder
Error using getDeployments (line 64)
startDialog.dataDir.timeSeries is not set

Error in autoIMOSToolbox (line 201)

Error in imosToolbox (line 79)"

please help me out.

Thanks in advance

**Comment by ggalibert** [comment]
Do you intend to use the toolbox in batch/auto mode on purpose? Have you documented your deployment database with some entries?

It seems you ran ```imosToolbox auto``` which is not recommended if you've never used the toolbox before.

Please read through
https://github.com/aodn/imos-toolbox/wiki/ToolboxInstallation
https://github.com/aodn/imos-toolbox/wiki/ToolboxConfiguration
https://github.com/aodn/imos-toolbox/wiki/UsingTheToolboxOverview
