### ISSUE TITLE
the MS-Access DDB provided in this project must be updated for use on 64 bit Office

### ISSUE THREAD

**Issue by phanindra1** [aodn/imos-toolbox#319]
Hi

While I am creating a database using OceanDB2015, it shows the compilation error and

Runtime error

 "the code in this project must be updated for use on 64 bit systems database ole32.dll"

guide me to solve this. Thanks and Any help will be appreciated.

**Comment by ggalibert** [comment]
Like the documentation says : https://github.com/aodn/imos-toolbox/wiki/ToolboxInstallation#configure-deployment-database
> Limitations have been observed such that it is not possible to open the current 32bit version of the deployment database with a Microsoft Access software 64bit.

Sorry about that, this is a known issue. The only way for you to open this file is to install a 32bit version of office.

**Comment by ggalibert** [comment]
One workaround is to convert the .mdb to .accdb. Be aware that once you convert to .accdb you can't go back to .mdb without a fair amount of manual copying to rebuild the .mdb.
