### ISSUE TITLE
imosToolboxBatch_Win64.exe not recognized as internal or external command

### ISSUE THREAD

**Issue by phanindra1** [aodn/imos-toolbox#320]
Hi

when I am running the imosToolboxBatch_Win64 file command window prompted as 

'imosToolbox_Win64.exe' is not recognized as an internal or external command,
operable program or batch file.

help

**Comment by ggalibert** [comment]
Could you please attach a screenshot?

The command to run is:
```
imosToolboxBatch_Win64.bat
```
from the imos-toolbox directory.

You can also double click on this .bat file.
