### ISSUE TITLE
Update Conventions global attribute to IMOS-1.4

### ISSUE THREAD

**Issue by mhidas** [aodn/imos-toolbox#323]
Since the Toolbox is now created netcdf files according to the latest version of the IMOS netcdf conventions, the global attribute should reflect this, i.e. 
```
                :Conventions = "CF-1.6,IMOS-1.4" ;
```
Currently it still says "IMOS-1.3"

**Comment by ggalibert** [comment]
Done https://github.com/aodn/imos-toolbox/commit/d817fefbfb4df3e950eaac80dddda216b2e7934e

**Comment by ggalibert** [comment]
in version 2.5.4
