### ISSUE TITLE
Installation issues with v2.5 on Windows Matlab-R2015b(64)/Access 2013(64)

### ISSUE THREAD

**Issue by rsignell-usgs** [aodn/imos-toolbox#324]
I tried following the installation instructions, using git to download the source code, and installing the database template at `C:\Users\rsignell\Documents\imos-database\OceanDB2015.mdb`.   I set this up mdb file as a ODBC data source, again following the instructions for "Setup Data Sources (ODBC)". 

When I try to open the above file in Access 2013, I get these two pop-ups: 
![2016-03-08_11-52-30](https://cloud.githubusercontent.com/assets/1872600/13609204/f592e63a-e525-11e5-8a56-0c9befea1937.png)
![2016-03-08_11-53-00](https://cloud.githubusercontent.com/assets/1872600/13609210/f8fa5fa6-e525-11e5-921a-97141f8c85c7.png)

and then when I try to run `imosToolbox_Win64.bat`, I get this pop-up:
![2016-03-08_11-56-49](https://cloud.githubusercontent.com/assets/1872600/13609236/0f491a7c-e526-11e5-8f5e-ba1775ce7dc1.png)

I suspect I'm missing a few steps or misconfigured something?

The only thing I set in `toolboxProperties.txt` was:
```
% filename or ODBC DSN of MS-ACCESS deployment database
% ex. : /home/ggalibert/OceanDB.mdb or imos-ddb
toolbox.ddb = C:\Users\rsignell\Documents\imos-database\OceanDB2015.mdb
```

**Comment by ggalibert** [comment]
I might need to update this section : https://github.com/aodn/imos-toolbox/wiki/ToolboxInstallation#configure-deployment-database as I thought that although the MS Access deployment database file is 32bit it was possible to open it with Access 2013 64bit. As a workaround, you can follow these instructions : https://github.com/aodn/imos-toolbox/wiki/ToolboxInstallation#with-ucanaccess-jdbc-drivers

Running imosToolbox_Win64.bat (standalone version) is missing this step : https://github.com/aodn/imos-toolbox/wiki/ToolboxInstallation#install-matlab-component-runtime

**Comment by ggalibert** [comment]
Also to be clear, according to the wiki installation documentation, the following in your toolboxProperties.txt:
```
% filename or ODBC DSN of MS-ACCESS deployment database
% ex. : /home/ggalibert/OceanDB.mdb or imos-ddb
toolbox.ddb = C:\Users\rsignell\Documents\imos-database\OceanDB2015.mdb
```
assumes you're not using the .mdb file as an ODBC source but that you would like to simply use UCanAccess JDBC API to read it. Which is the solution I recommend for you since your Office version is 64bit.

**Comment by SMeredyk** [comment]
Convert the .mdb to .accdb and this should help with your errors. Be aware that once you convert to .accdb you can't go back to .mdb without a fair amount of manual copying to rebuild the .mdb.
