### ISSUE TITLE
Time value for burst averaged data is not centred by default?

### ISSUE THREAD

**Issue by ggalibert** [aodn/imos-toolbox#329]
Comment from @sspagnol in https://github.com/aodn/anmn-internal-discussions/issues/7#issuecomment-194000497 :

> Comment about application of timeOffsetPP in relation to burst data that has been averaged eg RDI currents or wave parameters from WavesMon processed NEMO data.
> Consider an RDI configured to take 60 pings at 2 sec interval, start time to 01-Jan-2016 11:59:00. The toolbox will have the first ensemble time at 01-Jan-2016 11:59:00 whereas I think that the ensemble should have a timestamp of 01-Jan-2016 12:00:00. So currently have to apply timeOffsetPP to correct this, which isn't handle on a reprocessing job.
> Similar situation with LOG9 output from WavesMon processing, the time associated with the wave parameters is the time of the start of the burst, not the centered time of the burst.
> So first need to decide if we (I) should be time centering averaged burst data. If yes then how to make it seemless and hence require no intervention in a reprocessing job. If no make sure the end user understands this and there is enough information in the cd file to allow them to do the operation themselves.

I agree, we should be time centering the averaged burst data. However, shouldn't we try to fix the instrument parser in the toolbox to assign the correct time stamp rather than trying to correct/pre-process data read by some faulty parsers?

**Comment by sspagnol** [comment]
Agree that it should be done at the parser stage, but wasn't sure what everyone else is doing or thinks about it.

**Comment by ggalibert** [comment]
Ok, so according to the Commands and Output Data Format format, we would need to read the number of Pings Per Ensemble (WP) and the amount of time between ping groups in the ensemble or Time Per Ping (TP) to infer the Ensemble Interval (TE) following `TE = WP x TP` .

Finally, the time stamp for a data would be `Time Start of Ensemble + TE/2` .

**Comment by sspagnol** [comment]
RDI: should handle the most used case, need to check what happens if the user is collecting single ping data.

Other burst averaged instruments to consider

RBR XR-420-TG
In readXR420/readData: need a 
```
if isfield(header, 'averaging_time_period')
data.time = data.time + header.averaging_time_period/86400; %assume averaging time is always in seconds
end
```

RBR TGR-2050
Annoyingly the averaging information isn't carried through into the exported RText engineering file, but is present in the original hex file. This might be fixed in a future version of Ruskin, but in the mean time will have to modify readXR620 to parse header of both the txt and hex file.

SBE(16plus,16plusV2,19plus,19plusV2) : a confusing mess :)
The offset would be (if NCYCLES is set)
((NCYCLES-1) * ((1/samfreq)/86400) / 2 + {pump run time offset} + {DelayBeforeSampling}
ie. sampling at samfreq Hz (think its always 4 Hz for these models), but will have to be careful if this code is also used to read CTD cnv (like SBE25plus or SBE9). Mods to go into SBE19Parse/parseInstrumentHeader and SBE19Parse/genTimestamps. BUT need to find out what is written out in cnv file, NCYLES & PUMPMODE & MOOREDPUMPMODE &  DelayBeforeSampling are the commands affecting all this, but don't know what is in the resultant cnv file header.

**Comment by ggalibert** [comment]
For RBR XR-420-TG
In readXR420/readData: I think you meant
```matlab
if isfield(header, 'averaging_time_period')
  data.time = data.time + (header.averaging_time_period/86400)/2; %assume averaging time is always in seconds
end
```
You might have forgotten to divide the averaging period by 2 so that time positions itself in the middle of the averaging period.

**Comment by ggalibert** [comment]
Time stamp has been fixed in RDI workhorse and RBR XR 420 following your recommendations in master and 2.5 :
https://github.com/aodn/imos-toolbox/commit/54f4df699619fc956b40e6e0645b1cebf31dcb65
https://github.com/aodn/imos-toolbox/commit/17bb1b886d8216fb6dca88c96eb75c24d18f0baf

Please let me know about your progress regarding SBEs.

**Comment by ggalibert** [comment]
@petejan says:



Is this really a good idea? timestamp in the middle of the time is not necessarily 'correct'.

For CF a cell method should be specified as time: mean and a time bounds to indicate where the mean has been taken over.

http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch07s03.html

The RDI instrument does this processing internally and outputs the timestamp as the time at the start of the average, for FV00 files I don't think changing the timestamps is such a good idea, just document what the instrument has put out.

Sea-Bird pump and timestamp at the end. Maybe the ADCP just follows the convention of acoustics where it’s the time the ping was sent, not the received time, time that the ping was sent makes more sense for a single ping, your coding will not work well for single ping mode, it will give the midpoint of the ping not the time of the first ping. Instead of changing the time (which makes these files different from NetCDF files from other sources, e.g. on OceanSITES) how about just documenting what has happened? From the CF conventions, http://cfconventions.org/faq.html#time_gridpoint indicates generally the mid point is used, but in this case where the RDI convention uses the time of the first ping, I think we should stick to that.

**Comment by ggalibert** [comment]
It seems Nortek is applying the same convention as RDI : http://www.nortek-as.com/en/knowledge-center/forum/current-profilers-and-current-meters/579860283

**Comment by ggalibert** [comment]
@petejan, how is OceanSITES reporting ADCP times and how do they describe it? 

-Nature of the time: start, middle or end of the measurement?
-Structure of the measurement: number of pings, time between pings?

**Comment by ggalibert** [comment]
I've decided not to change time stamps for now but started to document where is the time stamp for some datasets and what is the average period. See https://github.com/aodn/imos-toolbox/commit/696cd32f954aa5b01c820d85e3d98f3c4b538e00

**Comment by sspagnol** [comment]
Ok. And how will this all be represented in the final netcdf file?

Will you have to add cell_methods and time boundaries as per
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch07s03.html
to keep it cf compliant?

Simon.

**Comment by ggalibert** [comment]
For now the only changes are:
-TIME variable attribute 'comment'  = ['Time stamp corresponds to the start of the measurement which lasts ' num2str(user.AvgInterval) ' seconds.']
-New TIME variable attribute 'seconds_to_middle_of_measurement' = user.AvgInterval/2
-New global attribute 'instrument_average_interval' = user.AvgInterval

It is not mandatory to use cell_method to be CF compliant.

These above changes are quick fixes to keep track of an information which wasn't recorded before is: 
-where is the time stamp (start, middle, end of measurement?),
-what is the duration of average measurement.

This doesn't mean that we couldn't decide to consistently move the time stamps to the middle of the averaging period later, if we agree it's the best practice.

**Comment by petejan** [comment]
Why not just use what CF specifies for cell_methods at http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch07s03.html

Create a time attribute
time:bounds = "time_bnds"

And add a dimension
nv = 2

And add a variable
double time_bnds(time,nv);

and populate the time_bnds(…,1) with the time variable and time_bnds(…,2) with time at the end of the averaging period

**Comment by ggalibert** [comment]
Could do but it's a bit overkill when the averaging period is consistently the same.
