### ISSUE TITLE
SBE3x.m fails where no salinity and version 2 download file

### ISSUE THREAD

**Issue by petejan** [aodn/imos-toolbox#344]
Download file contains 

 * do not output salinity with each sample

which gets read as outputting salinity by the parser

```
diff --git a/Parser/SBE3x.m b/Parser/SBE3x.m
index 443c431..04210fa 100644
--- a/Parser/SBE3x.m
+++ b/Parser/SBE3x.m
@@ -142,7 +142,7 @@ TIME_NAME         = 'TIME';
 header_expr       = '^[\*]\s*(SBE\S+)\s+V\s+(\S+)\s+(\d+)$';
 cal_coeff_expr    = '^[\*]\s*(\w+)\s*=\s*(\S+)\s*$';
 sensor_cal_expr   = '^[\*]\s*(\w+):\s*(.+)\s*$';
-salinity_expr     = '^* output salinity.*$';
+salinity_expr     = '^[\*] output salinity.*$';
 pressure_cal_expr = ['^[\*]\s*pressure\s+S/N\s+(\d+)'... % serial number
                      ',\s*range\s*=\s*(\d+)'         ... % pressure range
                      '\s+psia:?\s*(.+)\s*$'];            % cal date including Seaterm v2 variation format
@@ -201,9 +201,11 @@ sample_data.meta.featureType            = mode;
 %
 % The third type of line is an indication of whether salinity is output in
 % the data. It is literally:
-%
 %   * output salinity with each sample
 %
+% as opposed to
+%   * do not output salinity with each sample
+%
 % The fourth type of line is a name-value pair of a particular calibration
 % coefficient. These lines have the format:
 %
```

**Comment by ggalibert** [comment]
Could you please attach a data file so I can test?

**Comment by petejan** [comment]
Here is the file header

* Sea-Bird SBE37 Data File:
* FileName = C:\Users\jan079\Desktop\SAZ-16\SBE37-1778.asc
* Software Version 1.59
* Temperature SN = 1778
* Conductivity SN = 1778
* System UpLoad Time = Apr 13 2015 01:36:22
** SAZ-16 recovery
* ds
* SBE37-SM V 2.6b  SERIAL NO. 1778    13 Apr 2015  01:39:29
* not logging: received stop command
* sample interval = 600 seconds
* samplenumber = 102970, free = 87680
* do not transmit real-time data
* do not output salinity with each sample
* do not output sound velocity with each sample
* store time with each sample
* number of samples to average = 4
* serial sync mode disabled
* wait time after serial sync sampling = 30 seconds
* internal pump not installed
* temperature = 18.59 deg C


* S>
* SBE37-SM V 2.6b  1778
* temperature:  18-feb-13
*     TA0 = -9.265281e-05
*     TA1 = 2.919898e-04
*     TA2 = -3.643889e-06
*     TA3 = 1.895946e-07
* conductivity:  18-feb-13
*     G = -9.937344e-01
*     H = 1.439198e-01
*     I = -2.265878e-04
*     J = 4.082727e-05
*     CPCOR = -9.570000e-08
*     CTCOR = 3.250000e-06
*     WBOTC = 2.851069e-06
* pressure S/N 2409732, range = 1450 psia:  22-jul-2011
*     PA0 = 2.422122e-01
*     PA1 = 6.876183e-02
*     PA2 = -3.749023e-09
*     PTCA0 = 4.485933e+01
*     PTCA1 = 1.793848e-01
*     PTCA2 = -5.802373e-03
*     PTCSB0 = 2.616375e+01
*     PTCSB1 = -4.500000e-04
*     PTCSB2 = 0.000000e+00
*     POFFSET = 0.000000e+00
* rtc:  03-aug-07 
*     RTCA0 = 9.999750e-01
*     RTCA1 = 1.779688e-06
*     RTCA2 = -3.124183e-08


* S> 
*END*
start time =  28 Apr 2013  00:00:01
sample interval = 600 seconds
start sample number = 1
 19.9066, 0.00005,   14.278, 28 Apr 2013, 00:00:01
 19.9122, 0.00005,   14.278, 28 Apr 2013, 00:10:01
 19.9044, 0.00005,   14.278, 28 Apr 2013, 00:20:01
 19.9081, 0.00005,   14.278, 28 Apr 2013, 00:30:01
 19.9172, 0.00005,   14.278, 28 Apr 2013, 00:40:01
 19.9312, 0.00005,   14.278, 28 Apr 2013, 00:50:01
 19.9374, 0.00005,   14.278, 28 Apr 2013, 01:00:01
 19.9471, 0.00005,   14.278, 28 Apr 2013, 01:10:01
 19.9463, 0.00005,   14.278, 28 Apr 2013, 01:20:01
 19.9518, 0.00005,   14.278, 28 Apr 2013, 01:30:01
 19.9567, 0.00005,   14.278, 28 Apr 2013, 01:40:01

**Comment by ggalibert** [comment]
Thanks, will include this fix in the next release.

**Comment by ggalibert** [comment]
Fix in https://github.com/aodn/imos-toolbox/commit/b7ba1cf3f8e3bf38406db4c5f82f278245c34c49
