### ISSUE TITLE
dataFileStatusDialog.m incorrectly lists files if 

### ISSUE THREAD

**Issue by sspagnol** [aodn/imos-toolbox#351]
Regards line 85 of dataFileStatusDialog.m (https://github.com/aodn/imos-toolbox/blob/2.5/GUI/dataFileStatusDialog.m#L85)

[~, iSort] = sort([deployments.InstrumentDepth]);

If InstrumentDepth wasn't filled out in the database (e.g. the "instrument" listed was say an acoustic locator that doesn't provide any data stream so the person skipped entering a value for InstrumentDepth), then sorting would produced an incorrect iSort index which combined with next line

deploymentDescs = deploymentDescs(iSort);

which then cause the requestor to incorrectly display instrument/files.

Need some logic before to line 85 to handle this case. I know that the database should be correct but this code currently just powers on through and the user will things everything has been read in correctly. Especially hard to pick out if you have lots of instruments.

**Comment by ggalibert** [comment]
Fair enough, I will add some logic to handle this case.

**Comment by sspagnol** [comment]
For reference in order to get it going for me I changed the relevant code to

```matlab
          % for a mooring, sort instruments by depth
          theDepths = {deployments.InstrumentDepth};
          theDepths(cellfun(@isempty, theDepths)) = {NaN};
          [~, iSort] = sort(cell2mat(theDepths));
          deploymentDescs = deploymentDescs(iSort);
```

**Comment by ggalibert** [comment]
Ha! I've just release version 2.5.10 which includes a fix via this commit https://github.com/aodn/imos-toolbox/commit/94cccf9acec32ce410015dcaddd95739fc9fa2aa

I've done exactly like you.

**Comment by sspagnol** [comment]
Haha :)

Thanks for the fix. This bug was confusing me for a bit.

Simon.
