### ISSUE TITLE
Not all 1D variables are plottable by lineMooring1DVar

### ISSUE THREAD

**Issue by sspagnol** [aodn/imos-toolbox#356]
If user chooses a line plot 1D QC variable for which there is no autoqc available (eg CNDC, so other than user q'ed or in/out water or range qc'ed, rest of the points everything is qc flagged as raw) then the logic in lineMooring1DVar falls over (namely xMin and xMax will be set to NaN which causes the plot to fall over). So either have to not have the variable display as choice of change lineMooring1DVar logic to handle this.

**Comment by ggalibert** [comment]
Ok, I suggest to offer two modes of plotting in the Menu plots. 
Existing labels:
-QC
-non QC

will be replaced by:
-all data
-only good or non QC'd data

The first mode plots the data without any regard for flag values.
The second mode plots only the data that has a flag of value 0, 1 or 2 (non QC, good, probably good).

**Comment by sspagnol** [comment]
Sounds sensible to me.

**Comment by ggalibert** [comment]
Fixed in https://github.com/aodn/imos-toolbox/commit/70c7ebb6e18a6d344d2f1ba7efc1cf90e8f3cce9
