### ISSUE TITLE
Reprocessing Data for Lost instruments

### ISSUE THREAD

**Issue by FelicityMc** [aodn/imos-toolbox#368]
When using the toolbox for re-processing data from instruments flagged within the OceanDB as being lost (instruments->status = 0) the toolbox will not load the instrument as a deployment within the list of deployments for the mooring. For moorings with a lot of deployments it is easy to overlook this missing instrument. Recommend that the test on the instrument status is  #removed or modified.

**Comment by ggalibert** [comment]
I'm a bit surprised because the toolbox is not filtering anything depending on the Status field value of the Instruments table. 

Could you please send me a copy of your ddb and a detailed example that illustrates this problem?

**Comment by flickgit** [comment]
Hi Guillame,
It is a weird bug but I just tried to replicate it for the two instances that it occurred for me and I couldn’t. Maybe the issue I am having is that if depth information is missing then this also occurs. May have been coincidence that the issues were combined? I can confirm (Simon will back me up) that if the depth information is missing then the individual instrument/deployment does not appear as one of the deployments for the mooring.
Cheers
Flick

**Comment by ggalibert** [comment]
There used to be a bug regarding instrument without any nominal_depth documented. It has been indeed reported by @sspagnol and has been fixed since https://github.com/aodn/imos-toolbox/releases/tag/v2.5.12. See commits https://github.com/aodn/imos-toolbox/commit/7ad5f7e265fb42ec3dd4e614982e2c0ba89ad949 and https://github.com/aodn/imos-toolbox/commit/94cccf9acec32ce410015dcaddd95739fc9fa2aa

**Comment by flickgit** [comment]
Thanks Guillaume
I’ll apply the fix.
Cheers
Flick

**Comment by ggalibert** [comment]
As a reminder, I'll post here the link to the wiki where the installation via cloning the github imostoolbox repo is described: https://github.com/aodn/imos-toolbox/wiki/ToolboxInstallation#install-imos-toolbox. It enables users to update their toolbox without affecting their configuration (most of the time).

**Comment by ggalibert** [comment]
If any conflict arises when pulling updates, here is an example of how to deal with it: https://github.com/aodn/imos-toolbox/wiki/GitPullConflictExample .
