### ISSUE TITLE
Obsolete code warning for fastSaveas

### ISSUE THREAD

**Issue by sspagnol** [aodn/imos-toolbox#380]
Newer versions of Matlab give an "obsoleted in a future release" warning for line 11 of fastSaveas, namely

```matlab
frame_h = get(handle(hFig), 'JavaFrame');
```

Warning: figure JavaFrame property will be obsoleted in a future release. For more information see the JavaFrame
resource on the MathWorks web site. 

Googling around present some workaround one example is the last try/catch block listed in http://undocumentedmatlab.com/blog/figure-window-customizations

**Comment by ggalibert** [comment]
Thanks, should be fixed by https://github.com/aodn/imos-toolbox/commit/57acbac5b2ad90ca09b2259379de0cf3f68cdbfd

**Comment by ggalibert** [comment]
in 2.5.18
