### ISSUE TITLE
sort global attributes

### ISSUE THREAD

**Issue by petejan** [aodn/imos-toolbox#385]
In the generated netCDF files, it would be good to sort the attributes in alphabetic order to make it easier for humans to read.

This was requested by Marty for my generated netCDF files, and its a good idea. A checker test for this also? maybe.

**Comment by ggalibert** [comment]
Global attributes are actually already ordered by the toolbox in a way that is probably more meaningful than alphabetical. They are following the order they are listed in the [template files](https://github.com/aodn/imos-toolbox/blob/master/NetCDF/template/global_attributes_timeSeries.txt), which is grouping them by theme:
-what
-where
-when
-who
-how

From there, as long as the order is consistent, it should be pretty easy to find the information we're looking for.

I think Marty highlighted the need for some sort of order that would make ncdump output easier to read by humans. He probably suggested alphabetical order to you as a quick and dirty solution to enforce some sort of order in a random list of global attributes, but really the ordering performed by the toolbox is in our opinion better so I don't think I will change it.

**Comment by petejan** [comment]
Hmm, meaning full to someone. 

If your looking for something, then alphabetic is good.

Just sort them.

**Comment by ggalibert** [comment]
Indeed, they're sorted.

Difficult to please everyone on the sorting topic unfortunately.

**Comment by petejan** [comment]
I guess that will be my response to Marty in the future :-)

**Comment by ggalibert** [comment]
@mhidas maybe you can help me stop this fire.

Pete, what is your final benefit of having the toolbox to output global attributes sorted alphabetically as opposed to sorted by theme? How about I come and visit you to discuss this and/or other things, It might be more efficient than via GitHub.

**Comment by ggalibert** [comment]
Fixed by https://github.com/aodn/imos-toolbox/commit/d97b6ba2d9887981e643ae44b6ddd5e1acaa92d7 in https://github.com/aodn/imos-toolbox/releases/tag/v2.5.20
