### ISSUE TITLE
Application of manual qc to data that returns more that one sample_data structure

### ISSUE THREAD

**Issue by sspagnol** [aodn/imos-toolbox#387]
Sorry for the long winded issue, can't think of a nice way to describe this.

If you import and RDI what has waves you will have two sample_data entries but only one mqc file for the two files e.g. import adcp.000 and adcp.WVS, do some manual qc on wave parameters you end up with only one mqc file (adcp.mqc). But when you reimport data and redo historical QC, imosHistoricalManualSetQC.m will try to look for wave parameters when acting on sample_data structure from 000 file. Actuall error will occur in line 78

```MATLAB
sample_data.variables{idVar}.flags(dataIdx) = flag;
```
due to fact that
```MATLAB
idVar   = getVar(sample_data.variables, mqc(i).nameVar);
```
will return 0 (eg looking for variable WWSH from waves WVS file while working on sample_data struct from 000 currents file).

As a quick workaround for my use I just tested if idVar was zero and continued. For longer term solution either that (so can still use already created mqc files) or change the qc file name i.e. if import filename.ext then qc file is filename_ext.mqc or something.

**Comment by ggalibert** [comment]
It is a good idea that .mqc file name be fileName.ext.mqc from now on as opposed to fileName.mqc.

fileName.mqc needs to be supported for backward compatibility, but from now on, ADCP wave data manual QC needs to be in a fileName.ext.mqc file with fileName.ext being the file that includes wave data.

Will try to see if I can implement this.

**Comment by ggalibert** [comment]
Ok, got there. If you had made some manual QC on a wave dataset, then you will have to extract that or redo it so that it goes in a adcp.WVS.mqc file.

**Comment by ggalibert** [comment]
Should be fixed by https://github.com/aodn/imos-toolbox/commit/b06dd10c23def612c87c7bb2e035cc62574a97f6 in https://github.com/aodn/imos-toolbox/releases/tag/v2.5.20 . New file naming convention is fileName.ext.mqc / .pqc .
