### ISSUE TITLE
CTD profile data needs to be depth-binned for FV00

### ISSUE THREAD

**Issue by mhidas** [aodn/imos-toolbox#393]
CTD cast files like [this one](https://github.com/aodn/imos-toolbox/files/605477/IMOS_ANMN-SA_CDEFKOSTUZ_20160914T141403Z_JL03_FV00_Profile-SBE-19plus_C-20161122T024608Z.nc.zip) where the input data are not depth-binned end up with a DEPTH coordinate variable that is not monotonically ordered. This is not allowed by CF (although currently only picked up by the IMOS checker). The FV00 file output for such data should be depth-binned, just as for the FV01 vile.

**Comment by ggalibert** [comment]
Fixed by https://github.com/aodn/imos-toolbox/commit/57eeb57cd510561fb8373d5c27a578a75e7f34c4 in v2.5.21
