### ISSUE TITLE
Toolbox Long Filenames in Windows 7

### ISSUE THREAD

**Issue by FelicityMc** [aodn/imos-toolbox#410]
The longer filenames being produced by more recent versions of the toolbox are problematic with the Windows 7 path/filename being restricted to 259 characters. In particular the filename produced for the RDI instruments is excessively long, e.g.
IMOS_ANMN-QLD_AETVZ_20160330T055900Z_GBRCCH_FV00_GBRCCH-1603-Sentinel-or-Monitor-Workhorse-ADCP-81.5_END-20161001T054900Z_C-20170119T225517Z.nc
Filename > 140 chars. Severely restricts ability to move these files in any nested directory environment.

**Comment by ggalibert** [comment]
I understand your problem, removing 20 characters to the ADCP file might fix this for now but there might be times where this will still come back.

I can see that in Windows 10 you can enable NTFS long path support which would fix this issue once and for all.

**Comment by ocehugo** [comment]
closing since:

1. reducing fields in the file name (and the conventions) is not an option ATM or in the future.
2. I Updated the wiki to require a minimum windows partition with long filename support (>160 chars).
3. Windows 10 now supports 250 characters.
