### ISSUE TITLE
Plot Graphics Cropped

### ISSUE THREAD

**Issue by FelicityMc** [aodn/imos-toolbox#412]
Plot graphics produced when netcdf files are exported are cropped on the bottom. Example attached.
![imos_anmn-qld_gbrhis_fv01_gbrhis-1603_line_cphl_c-20161103t055437z](https://cloud.githubusercontent.com/assets/17605815/22278343/745fbd4e-e30e-11e6-9a9f-0d2ada641361.png)

**Comment by ggalibert** [comment]
* I suppose you use the toolbox version 2.5.24 on Windows 7?
* Are you using the toolbox in standalone or with your own Matlab install? If own Matlab, which version?
* What is you screen configuration (how many and how are they arranged next to each other)?

**Comment by ggalibert** [comment]
* Did that happen in interactive or auto mode use?

Tried two screens of different sizes next to each other horizontally in Windows 7 with both Matlab R2012b and R2016b and couldn't reproduce this issue.

**Comment by ggalibert** [comment]
Commits ca1020c and 53f3997 implemented in v2.5.30 should fix the issue.

@FelicityMc please pull the changes from branch 2.5 to get to v2.5.30 in order to validate this fix. If the same problem subsists please re-open this issue.
