### ISSUE TITLE
 ea_thresh default value in counts while imosEchoIntensityVelocitySetQC uses decibels

### ISSUE THREAD

**Issue by alexandreforest** [aodn/imos-toolbox#419]
Just wondering why the routine imosEchoIntensityVelocitySetQC uses the ABSI variables (in decibels) while the ea_thresh default value is given in counts (default 30 counts suggested by Janet Sprintal). Should the routine be applied to ABSIC variables (in counts)  instead?

**Comment by ggalibert** [comment]
Good point, thanks for pointing that out! Will correct in the next release.

**Comment by ggalibert** [comment]
Fixed in v2.5.25: https://github.com/aodn/imos-toolbox/commit/0a6353e63967dbbdf808b78a16ed3f1812cb8e4f
