### ISSUE TITLE
WQM Raw file processing readWQMraw

### ISSUE THREAD

**Issue by NickMortimer** [aodn/imos-toolbox#436]
Line data(iBadTime) = [];

iBadTime not defined in script

Error says : Undefined function or variable 'iBadTime'.
	readWQMraw	(C:\Users\mor582\Documents\MATLAB\imos\Parser\readWQMraw.m: line 190)
	WQMParse	(C:\Users\mor582\Documents\MATLAB\imos\Parser\WQMParse.m: line 64)
	manualImport	(C:\Users\mor582\Documents\MATLAB\imos\FlowManager\importManager.m: line 166)
	importManager	(C:\Users\mor582\Documents\MATLAB\imos\FlowManager\importManager.m: line 91)
	flowManager	(C:\Users\mor582\Documents\MATLAB\imos\FlowManager\flowManager.m: line 50)
	imosToolbox	(C:\Users\mor582\Documents\MATLAB\imos\imosToolbox.m: line 80)

**Comment by ggalibert** [comment]
Thanks for this. Will be fixed in next release.

**Comment by ggalibert** [comment]
Fixed in v2.5.27 by https://github.com/aodn/imos-toolbox/commit/341eef99825bca794c2de14c7a1930237bcb6e99
