### ISSUE TITLE
errors due to oscillations on the un-binned data

### ISSUE THREAD

**Issue by anaredd** [aodn/imos-toolbox#445]
In the profile mode, when importing un-binned CTD data (to then run soakStatusPP and CTDDepthBinPP) using SBE19Parse, sometimes we get an error due to the fact that the data is not monotonically ordered, and hence, the position of the maximum depth does not match the length of the data, The toolbox then treates the profile as if contains upcast values (and not IMOS CTD profile compliant), which induces an error. Would it be possible to make posZMax=nData (i.e. ignore upcast values) in the parse if the data is un-binned data and maybe re-check if the profile is IMOS compliant after the binning?

**Comment by ggalibert** [comment]
Sorry about that, I have included [a check on monotonical dimension for NetCDF CF compliance](https://github.com/aodn/imos-toolbox/commit/ff712b6ab6a67adb5e6077e9e8efe1336a09a57b) in v2.5.23. While this works well in timeSeries mode, this is creating more problems than being useful in profile mode. Will probably remove this in the next release for profile mode.

**Comment by ggalibert** [comment]
Fixed in v2.5.28 by https://github.com/aodn/imos-toolbox/commit/7b65d42b2834c0771fd00a14b4a159b6a2edc9df
