### ISSUE TITLE
Density inversion test

### ISSUE THREAD

**Issue by ggalibert** [aodn/imos-toolbox#447]
As soon as we have multiple salinity measurement at different depths, we could conduct a density inversion test on the vertical to QC salinity data.

**Comment by ggalibert** [comment]
Test from ARGO:
```Matlab
% [delta_upbot,delta_botup,is_inv_dens] = test_density14(P,T,S,threshold)
% 
% INPUT:
%
% P(1,nlevel) pression (dB)
% T(1,nlevel) T in situ (°C)
% S(1,nlevel) S in situ (PSU)
% treshold : treshold used for detecting density inversion (0.03kg/m3)
%
% OUTPUT:
% delta_upbot (1,nlevel) : top to bottom test :  if delta_upbot >= 0.03kg/m3 flag 4 of the level i
% delta_botup (1,nlevel) : bottom to top test:  if delta_botup <= -0.03kg/m3 flag of the level i
% is_inv_dens (1,nlevel) : is_inv_dens=1 if level i should be flagued as bad (flag 4) ; ==0  otherwise

% You will need The ITS-90 version of the CSIRO SEAWATER library, which you can obtain from
% http://www.cmar.csiro.au/datacentre/ext_docs/seawater.htm.  Version 3.3   22-Sep-2010 
% 

function [delta_upbot,delta_botup,is_inv_dens] = test_density14(P,T,S,treshold)

if size(P,1)> 1
P=P';
end
if size(T,1)> 1
T=T';
end
if size(S,1)> 1
S=S';
end

%%
% From top to bottom :  two consecutive levels, i and i+1, are checked (Pi < Pi+1 )
%%
Pref = (P(1:end-1)+P(2:end))/2;

% rho_i(Pi, Ti, Si, Pref): potential density referenced to the mid-point Pref 
rhop_i = sw_pden(S(1:end-1),T(1:end-1),P(1:end-1),Pref);

% rho_ip1(Pi+1, Ti+1, Si+1, Pref): potential density referenced to the mid-point Pref 
rhop_ip1 = sw_pden(S(2:end),T(2:end),P(2:end),Pref);
delta_upbot = [rhop_i-rhop_ip1, NaN]; 

%%
% From bottom to top :  two consecutive levels, i and i+1, are checked (Pi > Pi+1 )
%%
Pref = (P(2:end)+P(1:end-1))/2;

% rho_i(Pi, Ti, Si, Pref): potential density referenced to the mid-point Pref 
rhop_i = sw_pden(S(2:end),T(2:end),P(2:end),Pref);

% rho_ip1(Pi+1, Ti+1, Si+1, Pref): potential density referenced to the mid-point Pref 
rhop_ip1 = sw_pden(S(1:end-1),T(1:end-1),P(1:end-1),Pref);
delta_botup = [NaN, rhop_i-rhop_ip1]; 

% test if there is density inversion with the 0.03kgm-3 criterion
is_inv_dens = delta_upbot>=treshold | delta_botup<=-treshold;
```

**Comment by ggalibert** [comment]
Argo Quality Control manual v2.7 says:
> 14. Density inversion
This test compares potential density between valid measurements in a profile, in both
directions, i.e. from top to bottom, and from bottom to top. Values of temperature and
salinity at the same pressure level P i should be used to compute potential density ρ i (or σ i
= ρ i − 1000) kg m −3 , referenced to the mid-point between P i and the next valid pressure
level P i+1 . A threshold of 0.03 kg m −3 should be allowed for small density inversions.
Action: From top to bottom, if the potential density calculated at the greater pressure is
less than that calculated at the lesser pressure by more than 0.03 kg m −3 , both the
temperature and salinity values should be flagged as bad data. From bottom to top, if the
potential density calculated at the lesser pressure is greater than that calculated at the
greater pressure by more than 0.03 kg m −3 , both the temperature and salinity values
should be flagged as bad data. Bad temperature and salinity values should be removed
from the TESAC distributed on the GTS.

**Comment by ggalibert** [comment]
v2.5.36 now includes a density inversion test for profile data via commit https://github.com/aodn/imos-toolbox/commit/ee83f35b2ca33b60006d99db8efff9cb0436b5b6

**Comment by ocehugo** [comment]
closing since this is already there.
