### ISSUE TITLE
display whole pofile for QCing 

### ISSUE THREAD

**Issue by anaredd** [aodn/imos-toolbox#455]
![capture](https://user-images.githubusercontent.com/17558169/28004940-f8eac07c-6586-11e7-8700-9e10c84f84e3.PNG)
When sing the 2.5.28 version of the toolbox, for each of the QC'd variables the interface only displays good and non-qc data, leading to different y-axis and making it quite hard to judge the profile as a whole (and hence manually QC data). While it is possible to actually plot all the data together, having a high number of subplots does not help either. Could it be possilbe to either display the whole profile (i.e. from surface) or even better be able to choose the axis limits?

**Comment by ggalibert** [comment]
Thanks for your feedback Ana, makes sense. Will try to fix this first by adjusting all Y axis consistently with min/max y values of any good or non qc'd displayed variable (in the case of this screenshot, would be 0 to 75). Later I might try to include a new button on the GUI to choose axis limits.

**Comment by ggalibert** [comment]
Ok, this change has been introduced in v2.5.25 to enable support of DepthProfile graphing mode when running the toolbox in timeSeries mode. Will fix to restore its initial behaviour when running the toolbox in profile mode which was to display any data with depth >= 0.

**Comment by anaredd** [comment]
Thanks G!

**Comment by ggalibert** [comment]
Fixed in [v2.5.29](https://github.com/aodn/imos-toolbox/releases/tag/v2.5.29) via commit https://github.com/aodn/imos-toolbox/commit/bdce59c582ed3ea18e8afdf46634aa0422054517
