### ISSUE TITLE
Single data point collected during a burst not handled in readECOraw.m

### ISSUE THREAD

**Issue by sspagnol** [aodn/imos-toolbox#485]
Have an instance of a downloaded NTU device with only one sample in a burst recorded, example data

04/04/17	20:31:34	700	106	531
04/04/17	20:31:35	700	95	530
04/04/17	20:31:36	700	102	530
04/04/17	20:31:37	700	98	530
04/04/17	20:31:38	700	99	530
04/04/17	20:31:39	700	98	530
04/04/17	21:01:35	700	97	57
04/04/17	21:31:40	700	98	530
04/04/17	21:31:41	700	118	530

the code handling burst sampling will fail on line 200 for the "04/04/17	21:01:35" line as there is only one data point (not a burst). Not sure what should happen in this case.

**Comment by ggalibert** [comment]
Didn't manage to reproduce an error on v2.5.36. Could you please send the exact error message and example of datasets and DDB?

**Comment by sspagnol** [comment]
This is annoying, I can't exactly remember where now either (thought line 205 from memory) , but do have (on the attached files)

```matlab
deviceInfo = readECODevice('NTUSB236_1709_cleaned.dev')
sample_data = readECOraw( 'NTUSB236_1709_cleaned.raw', deviceInfo, 'timeSeries' )
sample_data.meta

ans = 

  struct with fields:

               instrument_make: 'WET Labs'
              instrument_model: 'ECO 	NTUSB'
          instrument_serial_no: '236	'
                   featureType: 'timeSeries'
    instrument_sample_interval: NaN
     instrument_burst_interval: 1801
     instrument_burst_duration: NaN
```

Can't remember if ```instrument_sample_interval == NaN``` and ```instrument_burst_duration == NaN``` cause further problems in imosToolbox (probably yes).

In the loop start line 198, the following lines

```matlab
        timeBurst = time(iBurst(i):iBurst(i+1)-1);
        sampleIntervalInBurst(i) = median(diff(timeBurst*24*3600));
        firstTimeBurst(i) = timeBurst(1);
        durationBurst(i) = (timeBurst(end) - timeBurst(1))*24*3600 + sampleIntervalInBurst(i);
```
if have single point in burst ```timeBurst == []``` so ```median([]) == NaN``` (in Matlab R2017b at least), and so ```durationBurst(i) == NaN```.

A quick fix was (for this case)

```
    for i=1:nBurst
        if iBurst(i+1) - iBurst(i) == 1
            firstTimeBurst(i) = time(iBurst(i));
        else
            timeBurst = time(iBurst(i):iBurst(i+1)-1);
            sampleIntervalInBurst(i) = median(diff(timeBurst*24*3600));
            firstTimeBurst(i) = timeBurst(1);
            durationBurst(i) = (timeBurst(end) - timeBurst(1))*24*3600 + sampleIntervalInBurst(i);
        end
    end
```

assuming 'is this a burst file' tests works ok and this code is only run in burst case. This yields
 ```matlab
>> sample_data.meta

ans = 

  struct with fields:

               instrument_make: 'WET Labs'
              instrument_model: 'ECO 	NTUSB'
          instrument_serial_no: '236	'
                   featureType: 'timeSeries'
    instrument_sample_interval: 1
     instrument_burst_interval: 1801
     instrument_burst_duration: 6
```

[20171215_NTU.zip](https://github.com/aodn/imos-toolbox/files/1637253/20171215_NTU.zip)

**Comment by ggalibert** [comment]
Yes, `instrument_sample_interval == NaN` and `instrument_burst_duration == NaN` are the only concern to me.

Did fix this issue outside of the loop (possibly faster) this way:
```Matlab
    iNaNBurst = isnan(sampleIntervalInBurst); % it is possible that only one sample is output for a burst
    
    sample_data.meta.instrument_sample_interval   = round(median(sampleIntervalInBurst(~iNaNBurst)));
    sample_data.meta.instrument_burst_interval    = round(median(diff(firstTimeBurst*24*3600)));
    sample_data.meta.instrument_burst_duration    = round(median(durationBurst(~iNaNBurst)));
```

Will be implemented in v2.5.37.

**Comment by sspagnol** [comment]
Either way will work. Time spent in the loop is nothing (for files used so far) compared to time to read in the file.

**Comment by ggalibert** [comment]
Fixe in v2.5.37 via commit https://github.com/aodn/imos-toolbox/commit/0e6d8c69583a2d00b4eb6b4f7de6c3a9271e6bbc.
