### ISSUE TITLE
Plot CTD profiles separately

### ISSUE THREAD

**Issue by anaredd** [aodn/imos-toolbox#487]
Currently it is possible to load and QC a number of CTD profiles at the same time. However, while the toolbox produces a separate netCDF file for each of the the profiles, it plots them all together. If the number of profiles it too big, the legend is too lengthy and the graphics too small to see anything. We can modify linecCastVar.m to fit our needs, but it might be a good idea to add the capability to the toolbox and maybe let the user decide how to plot the profiles?

**Comment by ggalibert** [comment]
It is difficult to have an automated process and at the same time ask the user how to plot the profiles (together or independently).
Another solution could be to plot profiles together but for a maximum number of them (say 3 or 4?). Past this maximum we would produce independent plots of 3 or 4 profiles together. So for example if you have loaded/QC'd 10 profiles, then we would produce 3 plots of 4-4-2 profiles together.
What do you think of this?

**Comment by anaredd** [comment]
I see your point, in that case, I think I would stick to individual profiles rather than a random grouping of profiles, I think it will be clearer for everyone

**Comment by ggalibert** [comment]
Ok, will implement this in the next release.

**Comment by ggalibert** [comment]
Fixed in v2.5.38 via commits https://github.com/aodn/imos-toolbox/commit/4d7293b299e5a1499e6c24862c3c42728da38724 and https://github.com/aodn/imos-toolbox/commit/43925c287e86e3487ccf737bb5f13cb4997d61ca
