### ISSUE TITLE
Re-processing of only one instrument

### ISSUE THREAD

**Issue by ggalibert** [aodn/imos-toolbox#491]
> Do we have to re-process the whole mooring when only one instrument needs to be corrected? Re-processing the whole mooring doesn't seem very efficient.

Actually, you can load only one (or some) instrument(s) from a particular deployment using the toolbox. When you get to the "Confirm data files" window:
![screenshot from 2018-03-14 12-22-48](https://user-images.githubusercontent.com/3498686/37381005-2773315c-278f-11e8-89de-440652593b7e.png)

just select any instrument in the top list (can use keyboard's up / down arrows) and click "Remove deployment" or hit the "Delete" keyboard button to only keep the relevant instrument(s):
![screenshot from 2018-03-14 12-23-08](https://user-images.githubusercontent.com/3498686/37381010-2dd93a50-278f-11e8-9860-ad0f2c0e978e.png)

I usually don't recommend re-processing a single instrument unless the correction is minor and the toolbox user is aware of the following drawbacks:
- You won't be able to look at similar sensor on the same mooring for cross validation.
- You won't be able to infer DEPTH for this instrument from neighbouring P sensors.
- If the pressure/depth/nominal_depth data or flags are modified for this instrument then the neighbouring instruments without P sensor that might have used this instrument's pressure/depth data won't be updated accordingly.
- The diagnostic plots showing data for the whole mooring won't be updated accordingly.

Does that answer your question @CraigSteinberg ?

**Comment by CraigSteinberg** [comment]
@ggalibert Yes that answers it and i agree it only for a minor correction. Good to know.
