### ISSUE TITLE
timeDriftPP fails when start and end time the same

### ISSUE THREAD

**Issue by petejan** [aodn/imos-toolbox#499]
Setting the start and end time drifts the to the same time in timeDriftPP causes the new time to not have any values, as 

(offset_s:(offset_e-offset_s)/(length(time)-1):offset_e)';

generates no values.

Patch fixes this,

[timeDriftPP.m.patch.txt](https://github.com/aodn/imos-toolbox/files/1878025/timeDriftPP.m.patch.txt)

**Comment by ggalibert** [comment]
Thanks for this, will include in next toolbox version.

**Comment by ggalibert** [comment]
Fixed in v2.5.38 via commit https://github.com/aodn/imos-toolbox/commit/356965197b4872417ec8990c84aa13479685f681
