### ISSUE TITLE
Strange logic determining parameter list in GUI/mainWindow.m function displayLineMooringVar

### ISSUE THREAD

**Issue by sspagnol** [aodn/imos-toolbox#505]
In GUI/mainWindow.m function displayLineMooringVar, I have query about the logic used to collect parameter names, namely

```matlab
        lenSampleData = length(sample_data);
        paramsName = {};
        paramsCount = [];
        paramsName{1} = 'diff(TIME)';
        paramsCount(1) = lenSampleData;
        % get all params that are in common in at least two datasets
        for i=1:lenSampleData
            lenParamsSample = length(sample_data{i}.variables);
            for j=1:lenParamsSample
                sameParam = strcmpi(paramsName, sample_data{i}.variables{j}.name);
                if ~any(sameParam)
                    paramsName{end+1} = sample_data{i}.variables{j}.name;
                    paramsCount(end+1) = 1;
                else
                    paramsCount(sameParam) = paramsCount(sameParam)+1;
                end
            end
        end
        
        iParamsToGetRid = (paramsCount == 1);
        paramsName(iParamsToGetRid) = [];
```

1. Why only  ```%get all params that are in common in at least two datasets``` ?
2. If you only load one file,  entries in ```paramsCount``` array will be set to one and then all parameters will be removed and an empty ```paramsName``` array passed to listdlg, and then error thrown (which is what happend for me)

**Comment by ggalibert** [comment]
> Why only %get all params that are in common in at least two datasets ?

This feature in the Tools menu was to plot on a single figure all the measurements of a common parameter on a mooring. If you want to look at a parameter that is measured by only one instrument then just select this instrument and this parameter in the main window. 

I thought it would be easier if only the parameters that have been measured by more than one instruments are available in this feature.

> If you only load one file, entries in paramsCount array will be set to one and then all parameters will be removed and an empty paramsName array passed to listdlg, and then error thrown (which is what happend for me).

Ok, I might need to handle this better but the reason is because you only have one instrument, it didn't make sense to me to produce a mooring plot while the main window can already produce what you're after.

**Comment by sspagnol** [comment]
Ah. Understood. I liked the single figure as it was big (filled the hole plot planel, and I'm getting old) and didn't have all the QC flagged dots, and is a quick was to make sure I hadn't missed QC'ing out a spike (typically at begin/end of mooring)

**Comment by ggalibert** [comment]
Been thinking about making the main window display a bit more configurable. Say display flags or not, adjust axis limits to display all or good data only, etc... Might help in your case.

**Comment by ggalibert** [comment]
For information, I added 2 tickboxes in the main window to display flags or not and to display flagged bad data or not. Should help with regards to @sspagnol 's last comment above.

**Comment by ggalibert** [comment]
Via https://github.com/aodn/imos-toolbox/commit/e0bc98f6e8d26be424274822e3f11e330145ba20 and https://github.com/aodn/imos-toolbox/commit/371319f61a72a5967e4c6c4d21c5d6462da26635

**Comment by ggalibert** [comment]
in v2.5.39
