### ISSUE TITLE
Adding parser to read RBR Concerto CTD, RBR Maestro CTD  and RBR Solo T sensors' data

### ISSUE THREAD

**Issue by CCouzi** [aodn/imos-toolbox#507]
Hi Guillaume,
would it be possible for you to add parsers that extract data from those loggers?
Find attached one file for the Maestro and Concerto CTDs, I'll shortly send you an example file for the Solo T.

[Raw CTD and SoloT data for IMOS.zip](https://github.com/aodn/imos-toolbox/files/2139926/Raw.CTD.and.SoloT.data.for.IMOS.zip)

Thanks,
Cheers.

**Comment by ggalibert** [comment]
Closing for now.
