### ISSUE TITLE
Adding parser to read Sequoia LISST 100x data

### ISSUE THREAD

**Issue by CCouzi** [aodn/imos-toolbox#508]
Hi Guillaume,
Would you be able to add a parser that reads the data from a LISST branded Sequoia, model 100X?
Find attached an example of file.
Thanks!

[LISST data for IMOS.zip](https://github.com/aodn/imos-toolbox/files/2139937/LISST.data.for.IMOS.zip)

**Comment by ggalibert** [comment]
Closing for now.
