### ISSUE TITLE
ADCP processing needs to include sound speed

### ISSUE THREAD

**Issue by petejan** [aodn/imos-toolbox#518]
The parser for workhorse RDI adcp extracts the SoundSpeed from the binary datafile, but this does not get carried into the netCDF file.

**Comment by ggalibert** [comment]
I suppose this is to cover the case of a sound speed value being entered manually instead of using the default temperature reading?

**Comment by petejan** [comment]
To document what sound speed the instrument used to calculate the distances, either entered manually or calculated by the instrument

**Comment by ggalibert** [comment]
Fixed in v2.5.41 via https://github.com/aodn/imos-toolbox/commit/6703bc6d3b7657ec0b671eab83b571650b71043c
