### ISSUE TITLE
Bursting instruments need to have FV01 being burst averaged

### ISSUE THREAD

**Issue by ggalibert** [aodn/imos-toolbox#519]
Last week at the first Moorings long time series working group meeting it has been pointed out that bursting instruments like WQMs should have their bursts being averaged in the FV01 (FV00 retains the original data). This can be done with the implementation of a new pre-processing routine in the toolbox.

We need to agree on a method to do so though. In particular I suggest:
1. Bursts need to be identified rather than expecting them to be where they should.
2. All data in a burst is going to be averaged since there hasn't been any QC applied yet.
3. Averaging could be performed either with mean or median (median being less impacted by potential outliers). **TO BE DECIDED**.
4. In addition to the burst averaged value, we might want to output the min/max/count/standard deviation (or median absolute deviation?) found within each burst. This is what is currently done by AODN for FV02 burst averaged products. **TO BE DECIDED**.
5. The time stamp assigned to the burst averaged value would be the centre of the burst.

Please feel free to comment.

**Comment by ggalibert** [comment]
@CraigSteinberg, @sspagnol, @FelicityMc, @anaredd could you please let me know what you think about this?

**Comment by CraigSteinberg** [comment]
Yes this would be good. Stats would be a handy indicator if the median burst value was aberrant.

**Comment by ocehugo** [comment]
> 3. Averaging could be performed either with mean or median (median being less impacted by potential outliers). TO BE DECIDED.

> 4. In addition to the burst averaged value, we might want to output the min/max/count/standard deviation (or median absolute deviation?) found within each burst. This is what is currently done by AODN for FV02 burst averaged products. TO BE DECIDED

my humble opinion: do both (mean/median estimates), it's easy and can be useful in the QC itself later on.
Also, given the bursts, sensors, and variables can vary wildly, best to do both and not hand pick the "best" for each (maybe this will change somehow in time/space and worse: through sensors)

finally, comparison plot is easy if we got both ready to go.

**Comment by mphemming** [comment]
Just an idea, but may be too complicated. Perhaps you could try determining whether the average/median is 'representative' of the burst by automatically analysing the distribution of the measurements within the burst? in other words, checking whether the distribution is uni-/bi-/multi-modal. If the mean/median value for a particular burst is outside of a set threshold range from the mode/modes it could be flagged as 'bad'? or the 'bad' burst could be dealt with another way.

**Comment by petejan** [comment]
My thoughts are,

Treatment depends on the parameter and the instrument.

Fluorescence a median works well as the data is spiky.
Temperature an average work well as the data is generally slowly changing, and the resolution is generally higher than the change within a burst.
PAR, neither average or median work particularly well, nearest sample works well, or linear fit with time and calculate the value for a time from the linear fit.

The netcdf cell_methods should indicate what was done to the data.

Strictly the timestamp of the burst should have had the same treatment as the data, so the timestamp for the averaged data should be the average of the data timestamps.

Appropriate cell_methods should be added as to what the time stamp of the average, first time, mid-point, etc.

The appropriate cell method should be added to our ADCP data which is an ensemble average (ADCPs can also be configured in burst mode also), the deep water ADCPs use the first ping time as the timestamp, Craig Steinberg indicated that they use the midpoint timestamp so as not to bias the measurement effected by tides, this can be indicated by the cell_method in the netcdf file.

Could you fold the bust data into another dimension in the FV00 file? So create TEMP(TIME, burst_sample)? Where TIME is the time stamp of the start of the burst and bust_sample dimension is 0….9 for 10 samples within a burst.

Pete

**Comment by ggalibert** [comment]
> Could you fold the bust data into another dimension in the FV00 file? So create TEMP(TIME, burst_sample)? Where TIME is the time stamp of the start of the burst and bust_sample dimension is 0….9 for 10 samples within a burst.

The samples in a WQM burst are not always 1sec apart. By doing so we may loose a sample's actual timestamp.

**Comment by ggalibert** [comment]
Below are some of the [CF cell methods](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#appendix-cell-methods) available in CF1.7 that might be useful:

cell_methods | Units | Description
--- | --- | ---
point | u | The data values are representative of points in space or time (instantaneous). This is the default method for a quantity that is intensive with respect to the specified dimension.
maximum | u | Maximum
median | u | Median
minimum | u | Minimum
mean | u | Mean (average value)
mode | u | Mode (most common value)
root_mean_square | u | Root mean square (RMS)
standard_deviation | u | Standard deviation
sum_of_squares | u2 | Sum of squares
variance | u2 | Variance

**Comment by petejan** [comment]
If you define TEMP(TIME, burst_sample) and also a 

float burst_sample(burst_sample)
  : long_name = 'time of sample within the burst'
  : units = 'seconds'

Which is the sample time within the burst, as a float seconds

I built the burst sampled MRU data files like this, where acceleration, load etc is sampled at 200 ms for 10 mins every hour.

**Comment by ggalibert** [comment]
> float burst_sample(burst_sample)
> : long_name = 'time of sample within the burst'
> : units = 'seconds'

How do you re-create a date/time value from that? You must be storing the start time of each burst somewhere.

**Comment by petejan** [comment]
?From the TIME(TIME) coordinate, your sample variable becomes,


CHL(TIME, burst_sample)


________________________________

**Comment by ggalibert** [comment]
> Strictly the timestamp of the burst should have had the same treatment as the data, so the timestamp for the averaged data should be the average of the data timestamps.

The problem with this is we will have different TIME values between say TEMP, FLU2 and PAR.

**Comment by ggalibert** [comment]
The following parameters are measured from WQMs and NXCI CTDs:

IMOS code | averaging method | standard name (or long_name)
--- | --- | ---
TEMP | mean | sea_water_temperature
CNDC | N/A (not QC'd) | sea_water_electrical_conductivity
PRES_REL | mean | sea_water_pressure_due_to_sea_water
DEPTH | mean | depth
PSAL | mean | sea_water_practical_salinity
DOXY | mean | mass_concentration_of_oxygen_in_sea_water
DOX | mean | volume_concentration_of_dissolved_molecular_oxygen_in_sea_water
DOX1 | mean | mole_concentration_of_dissolved_molecular_oxygen_in_sea_water
DOX2 | mean | moles_of_oxygen_per_unit_mass_in_sea_water
DOXS | mean | fractional_saturation_of_oxygen_in_sea_water
FLU2 | median | fluorescence_in_sea_water
CPHL | median | mass_concentration_of_inferred_chlorophyll_from_relative_fluorescence_units_in_sea_water
CHLU | median | mass_concentration_of_inferred_chlorophyll_from_relative_fluorescence_units_in_sea_water
CHLF | median | mass_concentration_of_inferred_chlorophyll_from_relative_fluorescence_units_in_sea_water
TURB | median | sea_water_turbidity
DENS | N/A (not QC'd) | sea_water_density
PAR | linear interpolation | downwelling_photosynthetic_photon_flux_in_sea_water
SSPD | N/A (not QC'd) | speed_of_sound_in_sea_water
VOLT | N/A (not QC'd) | voltage

I assumed a mean would suit well to dissolved oxygen measurements while median would suit better to turbidity which can be a bit spiky like FLU2.

**Comment by ggalibert** [comment]
It's been agreed at the last QC summit that the FV01 will include burst data with better QC. See https://github.com/aodn/imos-toolbox/issues/543 and https://github.com/aodn/imos-toolbox/issues/542 . Important spikes that can be automatically flagged shouldn't be included in an averaging process.
