### ISSUE TITLE
CPHL, CHLF and CHLU are the same parameter with different attributes

### ISSUE THREAD

**Issue by ggalibert** [aodn/imos-toolbox#532]
CPHL, CHLF and CHLU should be made distinct in the comment variable attribute:

CPHL: conversion from fluorescence to chlorophyll-a using uknown coefficients (most likely factory ones though, would be good to confirm).
CHLF: conversion from fluorescence to chlorophyll-a using factory coefficients.
CHLU: conversion from fluorescence to chlorophyll-a using user coefficients.

**Comment by mhidas** [comment]
Is the conversion done by the instrument or the toolbox? Would it be possible and meaningful to record the actual values of the coefficients in a variable attribute?

**Comment by ggalibert** [comment]
> Is the conversion done by the instrument or the toolbox?

Conversion can be done either in the instrument and/or in the software used to produce .DAT files from 
.RAW files (the toolbox can ingest either .DAT and .RAW).

> Would it be possible and meaningful to record the actual values of the coefficients in a variable attribute?

Good idea, we need to check that the coefficients are present in the .RAW/.DAT files though.

Ideally, we should manage only one parameter (say CPHL) instead of 3 for the same thing to avoid confusion/burden of use and then document the coefficients in the variable attributes.

**Comment by petejan** [comment]
In the QCd data file for example,

http://thredds.aodn.org.au/thredds/dodsC/IMOS/ABOS/SOTS/2011/IMOS_ABOS-SOTS_OB_20110725_Pulse_FV01_Pulse-8-2011-FLNTUS-1215-34m_END-20120721_C-20180127.nc.html

I have,

CHPL: attributes,

sensor_depth: 34.0
sensor_depth_float: 34.0
sensor_depth_positive: down
calibration_1215_CALIBRATION_DATE: 2008-10-13
calibration_1215_CALIBRATION_FACILITY: WET Labs
calibration_1215_CH_ANALOG_DARK_COUNT: 0.072
calibration_1215_CH_ANALOG_MAX_OUTPUT: 4.99
calibration_1215_CH_ANALOG_RESOLUTION: 1.8E-4
calibration_1215_CH_ANALOG_SCALE_FACTOR: 10.0
calibration_1215_CH_DIGITAL_DARK_COUNT: 54.0
calibration_1215_CH_DIGITAL_MAX_OUTPUT: 4117.0
calibration_1215_CH_DIGITAL_RESOLUTION: 1.9
calibration_1215_CH_DIGITAL_SCALE_FACTOR: 0.0121
calibration_1215_TURB_ANALOG_DARK_COUNT: 0.06
calibration_1215_TURB_ANALOG_MAX_OUTPUT: 4.98
calibration_1215_TURB_ANALOG_NTU_VALUE: 2.51
calibration_1215_TURB_ANALOG_RESOLUTION: 1.8E-4
calibration_1215_TURB_ANALOG_SCALE_FACTOR: 5.0
calibration_1215_TURB_DIGITAL_DARK_COUNT: 47.0
calibration_1215_TURB_DIGITAL_MAX_OUTPUT: 4117.0
calibration_1215_TURB_DIGITAL_NTU_VALUE: 2056.0
calibration_1215_TURB_DIGITAL_RESOLUTION: 1.7
calibration_1215_TURB_DIGITAL_SCALE_FACTOR: 0.0057
sensor_name: WET Labs-FLNTUS
sensor_serial_number: 1215
name: Chlorophyll code as per IMOS data
units: mg/m3
standard_name: mass_concentration_of_chlorophyll_in_sea_water
long_name: mass_concentration_of_inferred_chlorophyll_from_relative_fluorescence_units_in_sea_water
valid_min: 0.0
valid_max: 40.0
_FillValue: NaN
contributor_name: Christina Schallenberg
contributor_role: flntus_data_qc
ancillary_variables: CPHL_quality_control
coordinates: TIME DEPTH_CPHL LATITUDE LONGITUDE

Regards,

Pete

**Comment by ggalibert** [comment]
# Chlorophyll variable name mystery
E. Klein
2019-04-18
Last run 2019-04-19 10:43:16

## INTRODUCTION
In the CTD profiles and WQM burst average data collection you might encounter different names for the derived chlorophyll parameter. In a quick revision of the full collections three different names exists:

- CHLF: Chlorophyll estimate from fluorescence readings using factory provided coefficients. In the ncdf metadata: “mass_concentration_of_inferred_chlorophyll_from_relative_fluorescence_units_in_sea_water,Concentration of inferred chlorophyll from relative fluorescence per unit volume of the water body,conversion from fluorescence to chlorophyll-a using factory coefficients,Milligrams per cubic metre,mg m-3”
- CHLU: Chlorophyll estimate from fluorescence readings using user provided coefficients. “mass_concentration_of_inferred_chlorophyll_from_relative_fluorescence_units_in_sea_water,Concentration of inferred chlorophyll from relative fluorescence per unit volume of the water body,conversion from fluorescence to chlorophyll-a using user coefficients,Milligrams per cubic metre,mg m-3”
- CPHL: Chlorophyll estimate from fluorescence readings using an unknown coefficient. In the ncdf metadata: “mass_concentration_of_inferred_chlorophyll_from_relative_fluorescence_units_in_sea_water,Concentration of inferred chlorophyll from relative fluorescence per unit volume of the water body,conversion from fluorescence to chlorophyll-a using unknown coefficients,Milligrams per cubic metre,mg m-3”

The idea is determine when and where those variables are present and to test if there are differences between the estimates when they are present in the same instrument.

## CTD profiles
### Data Collection
The data is pulled from the geoserver service using the following query:

`http://geoserver-123.aodn.org.au/geoserver/ows?typeName=anmn_ctd_profiles_data&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0*`

The metadata was pulled using the following query:

`http://geoserver-123.aodn.org.au/geoserver/ows?typeName=anmn_ctd_profiles_map&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0*`

The resulting table is stored locally so no need to repeat the geoserver query.

```r
## read CTD profiles from local file
CTD <- read_csv("IMOS_-_Australian_National_Mooring_Network_(ANMN)_-_CTD_Profiles.csv", skip=29)

## read metadata from the geoserver
CTD.map = read_csv("http://geoserver-123.aodn.org.au/geoserver/ows?typeName=anmn_ctd_profiles_map&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0*")


## set chlorophyll variables as numeric
CTD$CHLF = as.numeric(CTD$CHLF)
CTD$CHLU = as.numeric(CTD$CHLU)
CTD$CPHL = as.numeric(CTD$CPHL)
```

The collection contains 107570 CTD profiles from338 cruises

```r
## uncomment to re-run
## 
# CHL = CTD %>% group_by(file_id) %>%
#   summarise(CHLF = sum(!is.na(CHLF)),
#             CHLU = sum(!is.na(CHLU)),
#             CPHL = sum(!is.na(CPHL)))
# 
# 
# ## add metadata
# CHL = left_join(CHL, CTD.map)
# 
# ## get the name of the instrument from the thredds server
# ## as it is not in the .map file I need to get it from each individual file
# ## this operation could take ~5mins as there are ~1600 files to open
# urlPrefix = "http://thredds.aodn.org.au/thredds/dodsC/"
# instrument=character()
# 
# for (i in 1:nrow(CHL)){
#   print(i)
#   nc=nc_open(paste0(urlPrefix, CHL$url[i]))
#   instrument = append(instrument, ncatt_get(nc,0)$instrument)
#   nc_close(nc)
# }
# 
# CHL$instrument = instrument
# 
# write_csv(CHL, "CHL.csv")
```

```r
## read the metadata
## already processed file
CHL = read_csv("CHL.csv")
```
### Who is measuring what
A table of the instruments per chlorophyll variable

No instrument is reporting `CHLU`

No instrument is reporting more than one chlorophyll variable

```r
instrumentVariable = data.frame(Variable = c("CHLF", "CHLU", "CPHL"),
                                Instruments = c(paste0(unique(CHL$instrument[CHL$CHLF!=0]), collapse = ", "),
                                                paste0(unique(CHL$instrument[CHL$CHLU!=0]), collapse = ", "),
                                                paste0(unique(CHL$instrument[CHL$CPHL!=0]), collapse = ", ")))

knitr::kable(instrumentVariable)
```

Variable | Instruments
-- | --
CHLF | Seabird SBE19plus, SEABIRD CTD - SBE19PLUS V2 SEACAT, SEABIRD CTD - SBE 9 Plus, SEABIRD CTD - SBE19Plus, SEABIRD SBE19plus V2, SEA-BIRD ELECTRONICS SBE19PLUSV2
CHLU |  
CPHL | RBR XR620, SEA-BIRD ELECTRONICS SBE19PLUSV2, SEABIRD SEACATPLUS V 1.4D, SEABIRD SBE19 PLUS V 2.2C, SEABIRD SBE19 PLUS V 2.1, SEABIRD SBE19plus V2, Seabird SBE19plus, SEABIRD CTD - SBE19PLUS V2 SEACAT, SEABIRD CTD - SBE19Plus, SEABIRD CTD - SBE 9 Plus, SEABIRD SBE19plus

### CHL variables by Station

This table shows the number of profiles that include each of the variable per site_code.

```r
siteCHL = CTD %>% group_by(site_code) %>% summarise(CHLF = length(unique(file_id[!is.na(CHLF)])), 
                                                    CPHL = length(unique(file_id[!is.na(CPHL)])))

knitr::kable(siteCHL)
```


site_code | CHLF | CPHL
-- | -- | --
B1 | 0 | 1
B2 | 0 | 1
B3 | 0 | 1
B5 | 0 | 1
BMP070 | 0 | 9
BMP090 | 0 | 11
BMP120 | 0 | 19
CH050 | 0 | 18
CH070 | 0 | 29
CH100 | 0 | 30
CJ1 | 0 | 4
CJ2 | 0 | 4
CJ3 | 0 | 4
GA06N | 0 | 4
GA07M | 0 | 4
GA08L | 0 | 4
GA08N | 0 | 4
GA09K | 0 | 4
GA09M | 0 | 4
GA10J | 0 | 4
GA11I | 0 | 4
GA11M | 0 | 4
GA12H | 0 | 4
GA13M | 0 | 4
GA14F | 0 | 6
GA15G | 0 | 6
GA15M | 0 | 4
GA16H | 0 | 6
GA18J | 0 | 7
GA19K | 0 | 9
JL03 | 0 | 9
JL04 | 0 | 9
JL05 | 0 | 9
JL06 | 0 | 8
JL07 | 0 | 9
JL09 | 0 | 8
NRSDAR | 71 | 126
NRSESP | 19 | 0
NRSKAI | 0 | 60
NRSMAI | 0 | 94
NRSNIN | 1 | 9
NRSNSI | 2 | 105
NRSPHB | 0 | 124
NRSROT | 9 | 91
NRSYON | 57 | 45
PH025 | 1 | 91
PH050 | 0 | 91
PH100 | 46 | 81
PH125 | 2 | 91
PH140 | 0 | 1
SA01 | 0 | 1
SA02alt | 0 | 1
SA03alt | 0 | 1
SA04alt | 0 | 1
SA05alt | 0 | 1
SA06alt | 0 | 1
SA07alt | 0 | 1
SA08alt | 0 | 1
SA09alt | 0 | 1
SA10alt | 0 | 1
SA11 | 0 | 1
SA12 | 0 | 1
SAM2CP | 0 | 1
SAM3MS | 0 | 4
SAM5CB | 0 | 4
SAM8SG | 0 | 9
SC01 | 0 | 1
SC02 | 0 | 1
SC03 | 0 | 1
SC04 | 0 | 1
SC05 | 0 | 1
SC06 | 0 | 1
SC07 | 0 | 1
SC08 | 0 | 1
SC10 | 0 | 1
SC11 | 0 | 1
SC12 | 0 | 1
SE01 | 0 | 1
SE02 | 0 | 1
SE03 | 0 | 1
SE04 | 0 | 1
SE06 | 0 | 1
SE07 | 0 | 1
SE08 | 0 | 1
SE09 | 0 | 1
SE10 | 0 | 1
SE11 | 0 | 1
SE12 | 0 | 1
SG01alt | 0 | 1
SG02alt | 0 | 1
SG03alt | 0 | 1
SG04alt | 0 | 1
SYD100 | 0 | 0
SYD140 | 0 | 0
WACA20 | 0 | 7
WACASO | 0 | 1
WATR05 | 0 | 1
WATR10 | 0 | 6
WATR20 | 0 | 8

## WQM timeseries

### Data collection

The data (burst averaged collection) is pulled from the geoserver service using the following query:

data:  `http://geoserver-123.aodn.org.au/geoserver/ows?typeName=anmn_burst_avg_timeseries_data&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0&`

metadata:  `http://geoserver-123.aodn.org.au/geoserver/ows?typeName=anmn_burst_avg_timeseries_map&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0`

As the file are quite big, I will pull the data by site_code, one by one. Also see if there are concomitant measurements of two chlorophyll variables. The result table is stored for future needs.

```r
# get metadata first
WQM.map <- read_csv("http://geoserver-123.aodn.org.au/geoserver/ows?typeName=anmn_burst_avg_timeseries_map&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.")
## get the name of sites
sitenames = unique(WQM.map$site_code)


## 
## uncomment to re-run
##


# WQM.chl = data.frame(site_code = character(),
#                      CHLF = numeric(),
#                      CHLU = numeric(),
#                      CPHL = numeric(),
#                      CHLFCHLU = logical(),
#                      CHLFCPHL = logical(),
#                      CHLUCPHL = logical())
# 
# for (i in 1: length(sitenames)){
# 
#   print(paste0(i, " - ", sitenames[i]))
# 
#   GEOquery = paste0("http://geoserver-123.aodn.org.au/geoserver/ows?typeName=anmn_burst_avg_timeseries_data&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=(site_code%20LIKE%20'", sitenames[i], "')")
#   WQM.data = suppressMessages(read_csv(GEOquery))
# 
# 
#   WQM.chl = bind_rows(WQM.chl, data.frame(site_code = sitenames[i],
#                                           CHLF = length(unique(WQM.data$timeseries_id[!is.na(WQM.data$CHLF)])),
#                                           CHLU = length(unique(WQM.data$timeseries_id[!is.na(WQM.data$CHLU)])),
#                                           CPHL = length(unique(WQM.data$timeseries_id[!is.na(WQM.data$CPHL)])),
#                                           CHLFCHLU = ifelse(sum(!is.na(WQM.data$CHLF) & !is.na(WQM.data$CHLU))>0,
#                                                             TRUE, FALSE),
#                                           CHLFCPHL = ifelse(sum(!is.na(WQM.data$CHLF) & !is.na(WQM.data$CPHL))>0,
#                                                             TRUE, FALSE),
#                                           CHLUCPHL = ifelse(sum(!is.na(WQM.data$CHLU) & !is.na(WQM.data$CPHL))>0,
#                                                             TRUE, FALSE)
#                                           ))
# 
# }
# 
# write_csv(WQM.chl, "WQMchl.csv")

WQM.chl = read_csv("WQMchl.csv")

knitr::kable(WQM.chl)
```

site_code | CHLF | CHLU | CPHL | CHLFCHLU | CHLFCPHL | CHLUCPHL
-- | -- | -- | -- | -- | -- | --
NRSKAI | 0 | 2 | 0 | FALSE | FALSE | FALSE
SAM8SG | 0 | 0 | 0 | FALSE | FALSE | FALSE
GBRCCH | 0 | 6 | 19 | FALSE | FALSE | FALSE
ITFJBG | 0 | 2 | 10 | FALSE | FALSE | FALSE
NRSMAI | 0 | 0 | 53 | FALSE | FALSE | FALSE
GBRHIS | 0 | 0 | 15 | FALSE | FALSE | FALSE
SAM5CB | 0 | 0 | 0 | FALSE | FALSE | FALSE
GBROTE | 0 | 1 | 11 | FALSE | FALSE | FALSE
GBRLSH | 0 | 4 | 15 | FALSE | FALSE | FALSE
GBRPPS | 0 | 8 | 20 | FALSE | FALSE | FALSE
GBRMYR | 0 | 3 | 11 | FALSE | FALSE | FALSE
PH100 | 24 | 24 | 2 | TRUE | FALSE | FALSE
NRSNSI | 0 | 0 | 65 | FALSE | FALSE | FALSE
NRSYON | 1 | 16 | 16 | FALSE | FALSE | FALSE
SYD100 | 7 | 7 | 1 | TRUE | FALSE | FALSE
SAM1DS | 0 | 0 | 0 | FALSE | FALSE | FALSE
SAM2CP | 0 | 0 | 0 | FALSE | FALSE | FALSE
SAM3MS | 0 | 0 | 0 | FALSE | FALSE | FALSE
SAM4CY | 0 | 0 | 0 | FALSE | FALSE | FALSE
SAM6IS | 0 | 0 | 0 | FALSE | FALSE | FALSE
SAM7DS | 0 | 0 | 0 | FALSE | FALSE | FALSE
PIL050 | 0 | 0 | 1 | FALSE | FALSE | FALSE
NRSROT | 49 | 0 | 0 | FALSE | FALSE | FALSE
NRSESP | 34 | 0 | 0 | FALSE | FALSE | FALSE
NRSDAR | 0 | 4 | 14 | FALSE | FALSE | FALSE
NRSNIN | 0 | 2 | 16 | FALSE | FALSE | FALSE
DARBGF | 0 | 0 | 3 | FALSE | FALSE | FALSE
WATR20 | 0 | 0 | 1 | FALSE | FALSE | FALSE

At PH100 and SYD100 have concomitant measurements of CHLU and CHLF. Let’s explore the relationship between both.

### PH100

```r
i=12 ## PH100
GEOquery = paste0("http://geoserver-123.aodn.org.au/geoserver/ows?typeName=anmn_burst_avg_timeseries_data&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=(site_code%20LIKE%20'", sitenames[i], "')")
WQM.data = suppressMessages(read_csv(GEOquery))

plot(WQM.data$CHLU, WQM.data$CHLF, pch=19, cex=0.5, col="blue")
```

![image](https://user-images.githubusercontent.com/3498686/56934749-a0aff880-6b30-11e9-951e-4fb6fe5a58ea.png)

```r
model = lm(CHLU~CHLF, data=WQM.data)

CHLUCHLFbias.PH100 = mean(WQM.data$CHLU - WQM.data$CHLF, na.rm=T)

summary(model)
```

```
Call:
lm(formula = CHLU ~ CHLF, data = WQM.data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.07344  0.00609  0.00808  0.01263  0.32099 

Coefficients:
                Estimate   Std. Error t value            Pr(>|t|)    
(Intercept) -0.324784447  0.000078585   -4133 <0.0000000000000002 ***
CHLF         1.003793243  0.000006987  143657 <0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02605 on 115752 degrees of freedom
  (21305 observations deleted due to missingness)
Multiple R-squared:      1, Adjusted R-squared:      1 
F-statistic: 2.064e+10 on 1 and 115752 DF,  p-value: < 0.00000000000000022
```

For PH100 there is a calibration factor of 1.0037932 units of CHLF per unit of CHLU. The **mean bias** between CHLUand CHLF is **-0.3151658 mg/m³**.

### SYD100

```r
i=15 ## SYD100
GEOquery = paste0("http://geoserver-123.aodn.org.au/geoserver/ows?typeName=anmn_burst_avg_timeseries_data&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=(site_code%20LIKE%20'", sitenames[i], "')")
WQM.data = suppressMessages(read_csv(GEOquery))

plot(WQM.data$CHLU, WQM.data$CHLF, pch=19, cex=0.5, col="blue")
```

![image](https://user-images.githubusercontent.com/3498686/56935278-52e8bf80-6b33-11e9-9f88-174da7f67c22.png)

```r
model = lm(CHLU~CHLF, data=WQM.data)

CHLUCHLFbias.SYD100 = mean(WQM.data$CHLU - WQM.data$CHLF, na.rm=T)

summary(model)
```

```
Call:
lm(formula = CHLU ~ CHLF, data = WQM.data)

Residuals:
       Min         1Q     Median         3Q        Max 
-0.0178894 -0.0013190 -0.0009555  0.0050740  0.0062558 

Coefficients:
               Estimate  Std. Error t value            Pr(>|t|)    
(Intercept) -0.30773391  0.00003703   -8310 <0.0000000000000002 ***
CHLF         1.00122990  0.00003026   33087 <0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.004306 on 32081 degrees of freedom
  (13378 observations deleted due to missingness)
Multiple R-squared:      1, Adjusted R-squared:      1 
F-statistic: 1.095e+09 on 1 and 32081 DF,  p-value: < 0.00000000000000022
```
For PH100 there is a calibration factor of 1.0012299 units of CHLF per unit of CHLU. The **mean bias** between CHLU and CHLF is **-0.3065892 mg/m³**.

## CONCLUSIONS
Analysing the CTD profiles and the WQM instruments for the chlorophyll variables, this are the results of the exploration:

1. in the CTD profiles and the WQM burst average collections are three (3) different names for the chlorophyll, as separate variables: CHLF, CHLU, CPHL.
2. For the CTD collection:
- CHLU is not used anywhere in the CTD profiles. However it is used in 12 of the 28 WQM sites.
- The name of the variable is associated with the instrument producing the measurement.
- There are no cases with two CHL variables for the same profile exist
- There are few stations (most of the NRS) that have alternate CHLF and CPHL variables in different profiles during its existence.

3. For the WQM burst average collection
- All three variables could be found in the collection in different sites and different instruments
- Only at PH100 and SYD100 exist concomitant measurements of CHLU and CHLF. The mean bias between CHLU and  CHLF is -0.3151658 mg/m³ for PH100 and -0.3065892 mg/m³ for SYD100 in

## RECOMMENDATIONS

1. Add a new variable in each collection with the standard and unique name of CHL (and its corresponding burst statistics if applicable), and specify in the metadata the origin of the variable
2. Contact the BGC steering group to seek recommendation on what variable to use in case of the WQM register with CHLU and CHLF variables at the same timestamp.

**Comment by ocehugo** [comment]
Questions and some wishful thinking:
1. Why the names carry the sensor number? 
2. Is the set of calibration coefficient names always constant for a particular calibration method?
3. Should all netCDF files be kept with the historical calibration information?
4. Is the calibration method open for change for the same sensor? For example, should I expect in the future that the set of calibration coeff. names will change to "_CH_[X,Y,Z]" given the calibration method changed from "wetlabs" to "new_fancy_method_at_newlabs"? 

If 2-4 are positive, then I think we should dig out the variable attribute storage for first-class variables. This way, (a) it's easy to pick up the coefficients for re-evaluation, (b) all files are kept with the historical calibrations, (c) we can support different calibration methods with the same structure.


For example, we can establish a new dimension ```ncal```, to store the number of calibrations the sensor suffered, followed by a proper metadata variables  ```calibration_date(ncal), calibration_facility(ncal) ``` for date/facility.

The actual calibration coefficients would need other new dimensions ```cc,stringlen```  to hold the varnames  ```calib_coef_varnames(ncal,cc,stringlen)```. The actual values would be in ```calib_coef_values(ncal,cc)```. 

At any new calibration (method), ncal (cc) goes up. CC would also go up for any new calibration coef. name. To construct the name space, just evaluate ```func(calib_coef_varnames,calib_coef_values) -> structured namespace``` directly.


PS: the names above are as good as any other.

**Comment by ggalibert** [comment]
The scope of this issue is just to output only one name CPHL for all chlorophyl data inferred from fluorescence and document their known differences in attributes. For example:

> - conversion from fluorescence to chlorophyll-a using uknown coefficients (most likely factory ones though, would be good to confirm).
> - conversion from fluorescence to chlorophyll-a using factory coefficients.
> - conversion from fluorescence to chlorophyll-a using user coefficients.

Questions raised above should be treated separately. Calibration information yet has to be shared with the toolbox/ADON, see https://github.com/aodn/imos-toolbox/issues/301.
