### ISSUE TITLE
JFE Infinity logger parser do not support metadata for bursting instruments, depends on #532

### ISSUE THREAD

**Issue by ggalibert** [aodn/imos-toolbox#536]
The instrument_burst_* attributes are missing from NetCDF files generated by the infinitySDLoggerParse.m (used in WA at NRSROT - see [example file](http://thredds.aodn.org.au/thredds/catalog/IMOS/ANMN/NRS/NRSROT/Biogeochem_timeseries/catalog.html?dataset=IMOS/ANMN/NRS/NRSROT/Biogeochem_timeseries/IMOS_ANMN-NRS_EKTUZ_20180816T080000Z_NRSROT_FV01_NRSROT-1808-ACLW-USB-24_END-20181214T023003Z_C-20181217T041212Z.nc)).

**Comment by ocehugo** [comment]
@paulmalthouse  - you can zip the file(s) and drag n drop on the github box when editing a msg :)

**Comment by paulmalthouse** [comment]
hi guys, is this thread meant for me? we don't use any JFE instruments.

**Comment by ggalibert** [comment]
@mpsnell could you please send me an example of raw file to be processed by the toolbox?

**Comment by ggalibert** [comment]
> I can average the bursts if that is better. The sample interval is 0.1s.
-- @mpsnell

[infinity-burst.zip](https://github.com/aodn/imos-toolbox/files/3419645/infinity-burst.zip)

**Comment by ocehugo** [comment]
The problem here is that the CSV file got repeated entries at the same timestamp.

```csv
...
Date,Temp.[deg C],Chl-Flu.[ppb],Chl-a[ug/l],Turb. -M[FTU],Batt.[V],
2018/08/16 08:00:00,19.873,0.56,0.56,0.12,3.01,
2018/08/16 08:00:00,19.873,0.56,0.56,0.12,3.01,
2018/08/16 08:00:00,19.873,0.57,0.57,0.13,3.01,
2018/08/16 08:00:00,19.873,0.55,0.55,0.12,3.01,
2018/08/16 08:00:00,19.873,0.55,0.55,0.16,3.01,
2018/08/16 08:00:00,19.873,0.55,0.55,0.15,3.01,
2018/08/16 08:00:00,19.873,0.54,0.54,0.13,3.01,
2018/08/16 08:00:00,19.873,0.56,0.56,0.13,3.01,
2018/08/16 08:00:00,19.873,0.54,0.54,0.13,3.01,
2018/08/16 08:00:00,19.873,0.57,0.57,0.13,3.01,
2018/08/16 08:00:01,19.873,0.60,0.60,0.12,3.01,
2018/08/16 08:00:01,19.873,0.58,0.58,0.12,3.01,
2018/08/16 08:00:01,19.873,0.58,0.58,0.11,3.01,
2018/08/16 08:00:01,19.873,0.58,0.58,0.11,3.01,
2018/08/16 08:00:01,19.873,0.58,0.58,0.11,3.01,
2018/08/16 08:00:01,19.873,0.59,0.59,0.11,3.01,
2018/08/16 08:00:01,19.873,0.58,0.58,0.11,3.01,
2018/08/16 08:00:01,19.873,0.57,0.57,0.11,3.01,
```

this maps the median to zero, since the number of repeated entries is larger than the actual different measurements (line 62 on the reader):

```matlab
sample_data.meta.instrument_sample_interval = median(diff(data.TIME.values*24*3600));
```

Which in turn, led to ```sampling_interval == 0```.

The fix is simple - just mask the repeated entries and apply the median afterwards. However, I'm wondering what is the policy here: 

1. Simply raise error or
2. Try to overcome the repeated entries and continue (e.g. do average->calculate diffs-> (diffs==0 -> continue) | (diffs>0 -> raise error))

Also, there should be an assertion for sampling_interval == 0.  The GUI cannot fix this automatically and keep going after reading the file. It raises a tip only at finalization phase:

```matlab
Info : 413964 TIME first duplicate values (and their corresponding measurements) had to be discarded in /home/holiveira/tmp/infinity/JFE.csv. Try to re-play and fix this dataset when possible using the manufacturer's software before processing it with the toolbox.
```

I also could not continue on the GUI because I need to:

```matlab
please document site_nominal_depth or site_depth_at_deployment and either instrument_nominal_height or instrument_nominal_depth global attributes so that an actual depth can be computed from 1 or 2 other pressure sensors in the mooring
```

However, there is no option to set the depth in the GUI. I don't know where. Any quick way of specifing the nominal_depth on the UI I can quickly test/reproduce?

**Comment by ggalibert** [comment]
> Any quick way of specifing the nominal_depth on the UI I can quickly test/reproduce?

The best way to overcome this is to run a copy of the deployment database that has a reference to this dataset.

**Comment by ocehugo** [comment]
@mpsnell,

Are you aware of the case below - same time, two different CHLA/TURBF readings?

```
2018/08/16 08:00:00,19.873,0.56,0.56,0.12,3.01,
2018/08/16 08:00:00,19.873,0.57,0.57,0.13,3.01,
```

This is standard? Should I (a) keep as is, (b) average/median the duplicated set, (c) keep first or (d) keep last in the set ?

**Comment by mpsnell** [comment]
G’day Hugo

This instrument has been set to 0.1s sampling in the burst. I can average each burst if that is preferred.

Cheers
Mark

**Comment by ggalibert** [comment]
> I can average each burst if that is preferred

@mpsnell, this is more up to your team to tell us what you would like us to make available via the portal: bursting data or burst average?

If you think that the average of each burst is what 99% of the users will be looking for for their research then please provide the burst averaged data. Otherwise if the bursting data has significant scientific value to be available to AODN portal users then we should find a way to handle this dataset.

I have the feeling that in this case the burst averaged data is what should be available through the portal but please confirm.

**Comment by ocehugo** [comment]
@mpsnell,

I already included support to make the median of these measurements, but the times should be appropriately defined anyway.
The file should be self-describing. In this case, the time resolution is higher than what is reported. It is better to fix this in your software (higher time precsion reporting). If this is an instrument software limitation, let me know so I can document it  accordingly.

**Comment by ocehugo** [comment]
@mpsnell,
after discussing this with @ggalibert , I cannot proceed with averaging/median/etc this since this will have to go to FV00 - relative "raw" data.

Hence, the "raw" data need to be corrected - ie, the time variable needs more precision (if this is the time resolution you want to distribute).

sorry about the confusion

**Comment by ggalibert** [comment]
Mark, to clarify Hugo's comment above, all you need to do at this stage is to tell us what you would like us to make available via the portal: bursting data at 0.1s sampling rate or a burst average at a lower sampling rate?

**Comment by mpsnell** [comment]
G’day Hugo

The instrument has been set to 0.1s sampling in bursts but logs in seconds. I can average each burst before applying the toolbox. I am waiting for a response from our local CPHL guru regarding sampling rate and burst averaging. I will let you know.

Cheers
Mark

**Comment by mpsnell** [comment]
G’day Guillaume

The instrument has been set to 0.1s sampling in bursts but logs in seconds. I can average each burst before applying the toolbox. I am waiting for a response from our local CPHL guru regarding sampling rate and burst averaging. I will let you know.

Cheers
Mark

**Comment by mpsnell** [comment]
Okay, I will chase up our local guy for some direction on this.

**Comment by ocehugo** [comment]
Requirements:

- [ ] JFE data timestamps are corrected to millisecond measurements when reading.
- [ ] Timestamps are corrected based on the number of repeated timestamp entries.
