### ISSUE TITLE
Set of default comments available for manual QC

### ISSUE THREAD

**Issue by ggalibert** [aodn/imos-toolbox#545]
At the last QC summit @FelicityMc expressed a need for a default set of comments to be made available when perfoming some manual QC.

@FelicityMc could you please provide a first list of common comments to include?

**Comment by VvanDongenV** [comment]
Here below are some common comments that were presented over the QC meeting and could be included - any refinement and/or adding anymore comments to those ones welcome.

-	**Spike** (often seen in WQM burst data)
-	**Sensor not yet stabilized** (e.g. often seen in RDI > TEMP sensor)
-	**Data maxing out** (e.g. often seen with WQM > NTU sensor > TURB)
-	**Sensor drops to zero** (e.g. often seen with DOx or CNDC < PSAL)
-	**Sensor drops or unstable then recovers** (e.g. often seen with CNDC < PSAL)
-	**TEMP only used for velocity calculation** (e.g.  RDI)

**Comment by ocehugo** [comment]
my 2 cents:

I think a good idea is to provide examples of the manual qc comments - say pictures and a short description. 

several reasons:

1. Provides visual aid of what that problem looks like.
2. Can go into the manual and provide help to new users.
3. Can help in the development of automatic QC functions.

**Comment by ocehugo** [comment]
I came up with the following entities to allow this:

```python
SingletonSpikeComment : CommentEntity = {
'name' : "Singleton Spike" : str,
'description' = "An isolated measurement identified as abnormal" : str,
'operator': 'Hugo' : str,
'automatic': Or(1,0) : bool,

QcData: QcEntity = { 
'comments': [SingletonSpikeComment, ...]: List[CommentEntity]
'points': [SingletonSpikeMaskPoints, ...]: List[array]
}
```

The generation of the first entity is done by a function, while the second one is just simple assignment:

```python
SingletonSpikeComment = GenCommentEntity(name,description,operator,automatic);

QcData.comments = [SingletonSpikeComment, ...]
QcData.points = [SpikeMaskPoints, ...]
```

QcData is then processed/filled/feedback with the UI.

This enable tracing, and also several "CommentEntity" to be stored in a single structure. It can also allow more than one ```CommentEntity``` for the same set of points.

This may be related together with #548.

@ggalibert, are we currently tracking who is doing manual qc? What do you think about the above?

**Comment by ggalibert** [comment]
The scope of this issue is much simpler: instead of typing again and again the same comments when doing manual QC, the user would like to optionally be able to pick pre-formatted comments as identified above.

Your comments above are valid but need to be treated separately.

**Comment by ocehugo** [comment]
OK!

Since we are setting names to things, it's essential to decide the scope of each comment; otherwise, people may understand different bits.

Hence,

1. What the difference between ```Sensor not yet stabilized``` and ```Sensor drops or unstable then recovers```? The former is for the first time units the sensor is underwater, while the latter is related to problems somewhere in the middle of the time series?

2. What is the meaning of masking with ```TEMP only used for velocity calculation```? 

3. ```Sensor drops to zero```  -> This is for the "actual" drop in the signal until zero (e.g. ```masked=[32,31,25,20,15,5,0,0,0,0,0,0]```) ?

So far, my understanding is the following:

```
{
       % internal_code: comment
	'spike': 'spike',
	'stabilisation_period': 'Sensor not yet stabilised since deployment',
	'data_overflow': 'data at or above sensor limits',
        'zero_measurements': 'data measured is zero',
        'sensor_instability': 'sensor instability',
	'invalid_data': 'unexpected measurements within the sampling context',
}
```

**Comment by ocehugo** [comment]
pinging @VvanDongenV & @FelicityMc for approval of the above tag:comment.

May you provide an opinion about the above or any extra information you may wish to include in the string?
