### ISSUE TITLE
starmon mini header changed

### ISSUE THREAD

**Issue by petejan** [aodn/imos-toolbox#549]
StarODDI have changed the file header format to

```
#B	Created:	31/05/2019 11:51:00
##	Version	SeaStar	7.91
#5	Field separation:	0
#2	Date & Time:	1
#6	Decimal point:	.
#7	Date def.:	dd/mm/yyyy	/
#8	Time def.:	:
##	Axis	0	Temperature(°C)	clRed	FALSE
##	Series	0	Temp(°C)	clRed	0	Temp(°C)	2
##	Recorder	9	Starmon mini	4035
##	Chart	9T4035DAT	
#D	Data:	69802	01/08/2018 00:00:00	31/03/2019 08:45:00
1	01/08/2018 00:00:00	9.69
2	01/08/2018 00:05:00	9.65
3	01/08/2018 00:10:00	9.61
4	01/08/2018 00:15:00	9.59

```
The parser and Wiki needs updating to head files generated by the newer version of software

**Comment by ocehugo** [comment]
Guys,

this should be a change in place or a new reader option? For example, older files would still require the "old" reader right?

@petejan,
may you please provide the function call signature and an example file (old and new)!?


Requirements:
- [ ] new header reader is implemented
- [ ] old/new reader is selectable
- [ ] Tests for new reader is available

**Comment by ggalibert** [comment]
I suppose any old and new formats should be supported.

**Comment by petejan** [comment]
Attached example files from several sensors I have,

[starODDI-example.zip](https://github.com/aodn/imos-toolbox/files/3415169/starODDI-example.zip)

**Comment by ocehugo** [comment]
@petejan,

For completeness, our current test file repo is missing some Staroddi example files:

a. Star-oddi with temperature corrections 
b. Star-oddi with temperature in degF
c. Star-oddi with pressure corrections
d. Star-oddi with salinity data.
e. Star-oddi with pressure correction and salinity data.

any mini/dst-tilt/dst-ctd would do.

So far I have faked the above conditions based on the manual but it would be nice to have real files.

would you have any to provide to us?

Cheers

**Comment by petejan** [comment]
Attached data files from temperature sensors, conductivity, and pitch and roll senors,

[starmon.zip](https://github.com/aodn/imos-toolbox/files/3954074/starmon.zip)

Remember the date format changes based on the users PC settings, also the data export from the starmon software needs setting up correctly.

**Comment by ocehugo** [comment]
Great! I already got some of those, but the salinity one is particularly useful to increase coverage. I add an issue to keep track of missing files too - #624.

**Comment by ocehugo** [comment]
forgot to link the old parser names to the new parser.
