### ISSUE TITLE
crashing with matlab 2018b/2019

### ISSUE THREAD

**Issue by petejan** [aodn/imos-toolbox#551]
I'm getting this message

```
Error using  == 
Matrix dimensions must agree.

Error in mainWindow (line 261)
buttons(buttons == zoominb)       = [];

Error in displayManager (line 112)
  mainWindow(windowTitle, sample_data, states, 3, @stateSelectCallback);

Error in flowManager (line 65)
  displayManager(['imos-toolbox v' toolboxVersion], rawData, callbacks);

Error in imosToolbox (line 74)
  otherwise,      flowManager(toolboxVersion);
 
Reference to non-existent field 'serial_number'.

Error in genIMOSFileName>genDefaultFileNameConfig (line 192)
              sample_data.meta.serial_number    '-' ...

Error in genIMOSFileName (line 53)
  defCfg  = genDefaultFileNameConfig(sample_data, dateFmt, mode);

Error in exportManager (line 74)
      setNames{k} = genIMOSFileName(dataSets{1}{k}, extension);

Error in flowManager/exportNetCDFRequestCallback (line 388)
    exportManager(data, names, 'netcdf');

Error in displayManager/stateSelectCallback/exportNetCDFCallback (line 640)
      callbacks.exportNetCDFRequestCallback();

Error in displayManager/stateSelectCallback (line 144)
      case 'Export NetCDF',   exportNetCDFCallback();

Error in mainWindow/selectionChange (line 378)
        currentState = selectionCallback(...

Error in mainWindow/stateButtonCallback (line 444)
        selectionChange('state');
 
Error while evaluating UIControl Callback.
```
When clicking the export netCDF button

**Comment by sspagnol** [comment]
Maybe something to do with new graphics stuff in matlab, pan/zoom etc buttons don't live on the figure toolbar (https://www.mathworks.com/matlabcentral/answers/419036-what-happened-to-the-figure-toolbar-in-r2018b-why-is-it-an-axes-toolbar-how-can-i-put-the-buttons) . I have code like

```matlab
buttons(buttons == tb)            = [];
buttons(buttons == savefigb)      = [];
if verLessThan('matlab', '9.5')
    buttons(buttons == zoominb)       = [];
    buttons(buttons == zoomoutb)      = [];
    buttons(buttons == panb)          = [];
    buttons(buttons == datacursorb)   = [];
end

delete(buttons);
```

**Comment by ggalibert** [comment]
```code
Reference to non-existent field 'serial_number'.

Error in genIMOSFileName>genDefaultFileNameConfig (line 192)
              sample_data.meta.serial_number    '-' ...
```

Have a look why this error is generated.

**Comment by petejan** [comment]
Ok yes two issues, the serial_number causing the crash, can fix that, what the button fix?

@sspagnol can you push this to the code base if it works?

**Comment by ggalibert** [comment]
https://github.com/aodn/imos-toolbox/pull/552

**Comment by sspagnol** [comment]
PR created https://github.com/aodn/imos-toolbox/pull/552.

Think I asked at the last QA/QC summit if the supported version of Matlab is going to change. Would be nice if its >=R2018b.

**Comment by ggalibert** [comment]
> Think I asked at the last QA/QC summit if the supported version of Matlab is going to change. Would be nice if its >=R2018b.

Yes, it's in the scope of the next couple of releases.

**Comment by ocehugo** [comment]
@petejan,

Can you please provide the reproduction steps? I need to reproduce, move to #552, test it again and check for any side effects.

**Comment by petejan** [comment]
Just the changes from sspagnol are needed to fixup for the new matlab graph tools. The other error was due to change in my local copy.
