### ISSUE TITLE
Upgrade dev environment to Matlab R2018b or more recent.

### ISSUE THREAD

**Issue by ggalibert** [aodn/imos-toolbox#553]
All code should be ported to/supported by a version of Matlab R2018b or more recent.

**Comment by ocehugo** [comment]
@ggalibert,

I need some direction here. Should I track down and remove all legacy compatibility code? Should I keep then? Should I only allow running the GUI/routines with R2018b?

Please edit requirements below accordingly.

Requirements:
- [ ] Document legacy code
- [ ] Keep legacy code
- [ ] remove legacy code
- [ ] Block usage on runtimes<R2018b

**Comment by ggalibert** [comment]
To all imos-toolbox users: @petejan, @sspagnol, @VvanDongenV, @paulmalthouse, @mpsnell, @TimAus-NSW, @anaredd, @FelicityMc 

Are you currently using a version of Matlab older than R2018b? 

If not then we can just focus on having new versions from now on compatible with R2018b. Wiki pages will then be updated to reflect the official version of Matlab currently supported. I don't think we can forbid users to use more recent versions of Matlab although this is on their own responsibility.

**Comment by FelicityMc** [comment]
I am and that sounds like a good idea.

**Comment by TimAus-NSW** [comment]
2015b, but pretty sure i will be able to update to 2018b.

**Comment by anaredd** [comment]
I think is a good idea too, I use 2018a at the moment, but can update when needed.

**Comment by VvanDongenV** [comment]
I use 2018a - happy to update when needed too.

**Comment by sspagnol** [comment]
R2018b would do. Don't know about various institutions maintenance status (i.e. can they upgrade).

And if interested you can look at differences from R2018b - R2019a [here](https://au.mathworks.com/help/matlab/release-notes.html?rntext=&startrelease=R2018b&endrelease=R2019a&groupby=release&sortby=descending&searchHighlight=), actually can view diffs between any two releases. Was excited about update to netcdf 4.6.1, but it didn't help with support of strings.

**Comment by paulmalthouse** [comment]
Hi Guillaume,

I have to reinstall matlab on my new machine and I believe we have the option to have the latest version installed.

P

Paul Malthouse | Research Officer (Oceanography - Marine Ecosystems) |
Southern Australian Intergated Marine Observing System (SAIMOS)
SARDI Aquatic Sciences | Primary Industries and Regions SA – PIRSA | Government of South Australia |
2 Hamra Avenue West Beach SA 5024 | PO Box 120 Henley Beach SA 5022 | DX 66760
P: (08) 8429 0976 | M: 0431 559 341 | E: paul.malthouse@sa.gov.au<mailto:paul.malthouse@sa.gov.au> | W: www.pir.sa.gov.au/research<http://www.pir.sa.gov.au/research> T: @SA_PIRSA<http://twitter.com/sa_pirsa>
[cid:image005.jpg@01D3BF98.80F8F590][cid:image004.jpg@01D2A2F3.E3FAE8F0]


Service l Professionalism l Trust l Respect l Collaboration & Engagement l Honesty & Integrity l Courage & Tenacity l Sustainability

Disclaimer: The information in this e-mail may be confidential and/or legally privileged. Use or disclosure of the information by anyone other than the intended recipient is prohibited and may be unlawful.

**Comment by ocehugo** [comment]
great.

I think it's safe to put a stone here because the code will still work with old versions within 2.52.42.

The official supported version for 2.52.42 will be R2018b.

Policy:

1. From version>2.52.42, the current code will not change to support Matlab older than R2018b.
2. The current and next versions of the toolbox will still pretty much work with older versions but we will not guarantee that after 2.52.42.

Requirements:
- [ ] Readme is updated.
- [ ] Wiki is updated.
