### ISSUE TITLE
Handle case of WQM which didn't record one of it's primary variables

### ISSUE THREAD

**Issue by ggalibert** [aodn/imos-toolbox#557]
See PR https://github.com/aodn/imos-toolbox/pull/555 .

@sspagnol can you please upload a zip file of an example of this misbehaved instrument file?

**Comment by ocehugo** [comment]
@sspagnol , can you provide the test file(s)? 

@ggalibert, I'm just wondering if the requirements here are broader. Is this a problem that can occur in other readers besides WQM?

Requirements:
- [ ] A function to set attributes based on emptiness of root variables in WQM.
- [ ] Handle missing salinity
- [ ] function pass against files provided

**Comment by sspagnol** [comment]
Shortened example file attached. If we try and process this file with WQMHost to create dat file nothing is produced so had to import raw file in the toolbox (and hence code changes).

[WQM0197_002_example.zip](https://github.com/aodn/imos-toolbox/files/3404278/WQM0197_002_example.zip)

Regards "Is this a problem that can occur in other readers besides WQM?", I hope note. The WQM when it works, works well; when it falls over then its a pain. They are slowy being phased out.

**Comment by ocehugo** [comment]
@sspangol,

can you also post the function signature (aka how did you call it, at which step)? I can run the readWQMraw.m on the file but would like to see if there can be any side effects on the execution tree.

modifications are now in PR#561
