### ISSUE TITLE
label aquadopp battery voltage

### ISSUE THREAD

**Issue by petejan** [aodn/imos-toolbox#565]
The voltage variable in generated aquadopp files in unlabelled with what its measuring.

Change to label it battery voltage

[aquadopp-battery-voltage.zip](https://github.com/aodn/imos-toolbox/files/3415182/aquadopp-battery-voltage.zip)

Not sure that a long_name of voltage is all that useful in describing the variable.

**Comment by ggalibert** [comment]
This has implications for other parsers.

**Comment by petejan** [comment]
care to elaborate? is it that other parses should also be updated?

**Comment by ggalibert** [comment]
Yes, other parsers are using the `VOLT` code and `voltage` long_name.

**Comment by petejan** [comment]
Hmm that many,
```
C:\Users\jan079\ABOS\temp\imos-toolbox>grep -r --include="*.m" VOLT .
./Parser/addAWACWaveToSample.m:        'VOLT',               1,       waveData.Battery; ...
./Parser/addAWACWaveToSample.m:        'VOLT',               1,       waveData.Battery; ...
./Parser/aquadoppProfilerParse.m:    'BAT_VOLT',         1,              battery; ...
./Parser/aquadoppVelocityParse.m:    'BAT_VOLT',         1,  battery; ...
./Parser/awacParse.m:    'VOLT',             1,              battery; ...
./Parser/continentalParse.m:    'VOLT',             1,              battery; ...
./Parser/infinitySDLoggerParse.m:              data.VOLT.values = vertcat(values{:,i});
./Parser/infinitySDLoggerParse.m:              data.VOLT.comment = '';
./Parser/NXICBinaryParse.m:  sample_data.variables{10}.name = 'VOLT'; % battery voltage
./Parser/RCMParse.m:            name = 'VOLT';
./Parser/readSBE19hex.m:%CONVERTVOLTS Converts from raw A/D counts to voltage, as specified in the
./Parser/readWorkhorseEnsembles.m:% 1 XMIT VOLTAGE
./Parser/signatureParse.m:        'VOLT',             1,              data.(acquisitionMode{i}).Battery; ...
./Parser/workhorseParse.m:      'VOLT',               1,      voltage,        voltComment
./Parser/YSI6SeriesParse.m:        sample_data.variables{end}.name           = 'VOLT';
./Preprocessing/transformPP.m:% The user's most recent selections for each variable (e.g. 'VOLT_3' may
```
Although workhorseParse voltage is TX voltage not battery voltage and readSBE19hex is RAW voltage maybe

**Comment by ocehugo** [comment]
I need further directions here.

@petejan, can you provide an input file and the function call, so I can reproduce the unnamed label?
@ggalibert, can you explain why others need remappings? Apparently the VOLT output is a weak reference (i.e. can be several things in the instrument parameter). How to solve this issue ? new variable names?
@petejan, could you provide a simple one-to-one table for the different voltages you know about?

If we need to change that many readers, I would like to properly add references to specific ones (say workhorseParse voltage TX - See instrument manual page XYZ).

**Comment by petejan** [comment]
Here is an example aquadopp file, 

[SAZ20-2018.zip](https://github.com/aodn/imos-toolbox/files/3424899/SAZ20-2018.zip)

The voltage measurement should be battery voltage. 

from the above grep, its mostly contained as comments in the parser.m file, just needs some way documenting this in the netCDF file.
