### ISSUE TITLE
StarmonMiniParse.m file header formats changed

### ISSUE THREAD

**Issue by BecCowley** [aodn/imos-toolbox#622]
I have the following header formats in our latest Starmon Mini files: (Ignore the apostrophies at the start, put them in to stop auto markdown, screenshot for clarity)

![Screen Shot 2019-12-12 at 4 18 18 pm](https://user-images.githubusercontent.com/8251238/70684692-1ef58f80-1cfb-11ea-83c5-4e022f815adc.png)

'#B	Created:	25.09.2019 03:52:48
'##	Version	SeaStar	7.61
'#5	Field separation:	0
'#2	Date & Time:	1
'#6	Decimal point:	,
'#7	Date def.:	dd.mm.yyyy	.
'#8	Time def.:	:
'##	Axis	0	Temperature(?C)	clRed	FALSE
'##	Series	0	Temp(?C)	clRed	0	Temp(?C)	2
'##	Recorder	3	Starmon mini	3998
'##	Chart	3T3998DAT	
'#D	Data:	152105	15.04.2018 00:00:00	25.09.2019 03:20:00

The headerFormat in getHeader subfunction doesn't work with these headers:

headerFormat = '#%d\t%[^:]:\t%[^\r\n]';
headerContent = textscan(fileId, headerFormat, 'Delimiter', '');

Is it possible to get the format specifier updated soon? I can have a go if not!
Thanks

**Comment by BecCowley** [comment]
I have edited the StarmonMiniParse.m code. Will submit it soon.

**Comment by ocehugo** [comment]
@BecCowley, thanks but we already know about it and got implemented - just missing to merge #621 and release.

**Comment by BecCowley** [comment]
@ocehugo, I have pulled down the new code. Can you tell me now how do I make the toolbox use the new parser? It still is using the old StarmonMiniParse.m

**Comment by ocehugo** [comment]
@BecCowley, I forgot to put the new parser on the GUI because the src file lies in a different place - PR will be here soon.

FYI: The new parser is called "Staroddi" and substitutes StarmonMini and StarmonDST. It supports older and new versions of the headers.

**Comment by BecCowley** [comment]
@ocehugo OK. I thought since the new code had already been added to the master it would work. I figured out the name change, but I wasn't sure if I had to  nominate the parser in a .txt file somewhere. Let me know when it's ready to use. I can't do much till next year now.

**Comment by ggalibert** [comment]
Duplicate, see https://github.com/aodn/imos-toolbox/issues/549.

**Comment by ocehugo** [comment]
I shall explain myself - the parsers names will not be changed and the changes will be transparent (the change of names is internal only).  This is so to avoid conflict with instruments.txt files, db matches, etc. 

@BecCowley, you can use it if you merge https://github.com/aodn/imos-toolbox/pull/628 or wait it to be on master.
