### ISSUE TITLE
Parser for SBE39Plus instruments required

### ISSUE THREAD

**Issue by BecCowley** [aodn/imos-toolbox#638]
A parser for SBE39Plus instruments is needed. 
Sample files attached from EAC 2018-2019. Please can it be soon (in the next month?).

[Archive.zip](https://github.com/aodn/imos-toolbox/files/4075096/Archive.zip)

**Comment by sspagnol** [comment]
We use the SBE19 parser on the cnv file.

**Comment by ocehugo** [comment]
@BecCowley , yes, the SBE19 is the one to use.

The SBE namespace is a beast ATM and exists for historical and compatibility reasons - the SBE19 is usually the more general one.
