### ISSUE TITLE
New variables for SBE19 profiling parsing

### ISSUE THREAD

**Issue by stbyrnes** [aodn/imos-toolbox#658]
The SBE19 parser is not recognising the following variables (see attached file .cnv file):

CStarTr0: Beam Transmission, WET Labs C-Star [%]
par/log: PAR/Logarithmic, Satlantic [umol photons/m2/s]

Can they please be added? 

[YON20200306CFALDB.zip](https://github.com/aodn/imos-toolbox/files/4507966/YON20200306CFALDB.zip)

**Comment by ocehugo** [comment]
@stbyrnes, confirmed.

I can see that Beam Transmission is an optical property but I couldn't find a IMOS parameter for it - I quickly skimmed, but there is no percentage optical parameter to match. Hence, I will need more info if this is to be exported as a variable within the toolbox.

**Comment by stbyrnes** [comment]
@ocehugo, thanks.

No, there doesn't appear to a IMOS parameter for it, though I noticed a Beam attenuation parameter was added recently. Beam transmission is similar (and measured by the same instrument), but measured as a percentage transmission, which is used on all our Seabird CTD profilers. Simon Spagnol did some testing for me in our local AIMS toolbox and made the following additions to the convertSBEcnvVar.m file that appear to work:

 % CStarTr0 (percent)
    case {'CStarTr0'}
      name = 'BAT_PERCENT';
      comment = 'Beam Transmission, WET Labs C-Star [%]';

He also added 'par0x2Flog' to the case line for PAR as follows:
% PAR/Irradiance, Biospherical/Licor
    %par/sat/log - light sensor in SBE19plus assumed in umol photons/m2/s and implemented on #550
    case {'par0x2Fsat0x2Flog', 'par/sat/log', 'par0x2Flog'}
      name = 'PAR';
      comment = 'PAR/Logarithmic/ Satlantic';

Can these be added to the IMOS version?
Let me know if you require any further info.

**Comment by ocehugo** [comment]
Thanks @stbyrnes. Exactly  what I want - the actual expected name for the optical property. And yes, PAR needs this other name given we don't handle different encodings atm.

I may include this on top of #648 since it's related. Will poke here when in master

**Comment by stbyrnes** [comment]
Great. Thanks @ocehugo .
