### ISSUE TITLE
IMOS Feature Request: Support for Campbell Scientific CR1000 data tables

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aodn/imos-toolbox#67]
```
At our NRS sites (national reference stations) we use the CR1000 to log from 
various meterological sensors. The data is all stored in ASCII files, an 
example is attached. 

We also auto generate a sensorML file for each instrument, so metadata could 
potentially be imported from those records.  
```

Original issue reported on code.google.com by `rigb...@gmail.com` on 9 Jun 2011 at 12:27

Attachments:
- [YongalaNRS_Buoy_I10_Vaisala[1].dat](https://storage.googleapis.com/google-code-attachments/imos-toolbox/issue-67/comment-0/YongalaNRS_Buoy_I10_Vaisala[1].dat)

**Comment by ggalibert** [comment]
Haven't heard from Paul on this for ages.
