### ISSUE TITLE
imosTimeSeriesSpikeQC applied to 2D RDI variables

### ISSUE THREAD

**Issue by sspagnol** [aodn/imos-toolbox#676]
I have a situation where imosTimeSeriesSpikeQC is operating on an RDI, but the list of variables being considered is also including 2D variables (like ECUR etc), generated from 

```matlab
load_timeseries_variables(sample_data);
```

but when code gets to line 226

```matlab
 [l, r] = validBounds(pqc_var.flags);
```

```validBounds``` is operating on a 2D flags array, which I don't it's set up for, and in my case returns values which are then applied in a manner which doesn't make sense and causes it to fails (usually at line 236).

**Comment by ocehugo** [comment]
Thanks, confirmed. 
Yes, validBounds accepts only vectors. Problem here is that load_timeseries_variables is missing a size filter for those invalid variables
