### ISSUE TITLE
imosTiltVelocitytiltQC broken for ADCP

### ISSUE THREAD

**Issue by ocehugo** [aodn/imos-toolbox#680]
Tim sent me an email with TiltQC marking way more data than it should for ADCP.

The problem was introduced in 2.6.7 with code for current meters. The logic that handles the ADCP multidimensional array is incorrect (reversed). The problem was that the tests for ADCP were also incorrect with wrong dimensions in ROLL/PITCH, which allow this problem to pass unnoticed.

- [x] logic is corrected
- [x] tests are updated

**Comment by TimAus-NSW** [comment]
Can confirm fix works. Thanks.
