### ISSUE TITLE
Visual selection of DOX2 is not avialable in the Main window

### ISSUE THREAD

**Issue by ocehugo** [aodn/imos-toolbox#726]
A toolbox user found a strange behaviour on the main window, related to the variable visualisation selection.

>Hi all,
>For the ‘ticking boxes’ step (see attachment ‘toolbox_1.png’) there is initially only one tickbox, showing only dissolved oxygen in ml/l units. This is different from previous toolbox versions, but once you hit ‘QC data’ there are extra options to view the dissolved oxygen in umol/L and umol/kg, which need to be selected.

Seems a missing callback/update to the GUI window regarding new variables created at the PP level.

Requirements:
- [ ] DOX2 (and any other) is available to be selected right off the start, if available.

**Comment by ggalibert** [comment]
This is normal behaviour. By default, when landing on the main window, one can only select and view the original instrument data with no QC (the FV00 data). As soon as you hit the QC data button then you switch to being able to view the pre-processed and QC'd data (the FV01 data).

In this case DOX2 must have been derived from another measured parameters and hence is not available in the variable tick box when you are looking at the "raw" FV00 data.
