### ISSUE TITLE
adding Thetis profiler CTD and DO data formats

### ISSUE THREAD

**Issue by evacougnon** [aodn/imos-toolbox#771]
add the Thetis profiler CTD and DO data formats (SBE 49 and 43).
The Thetis is deployed off Rottnest (2 miles from the IMOS NRS) as part of the IMOS Satellite Remote Sensing facility.

[Thetis_samples.zip](https://github.com/aodn/imos-toolbox/files/8448441/Thetis_samples.zip) sent to AODN on 12/01/2022, from the SBE49 CTD on the Thetis profiler.
> I think that the SBE49 is also used on AUVs, it is not specific to the Thetis. On the Thetis, the CTD is connected to a custom datalogger (with several other instruments) and we use a specific file extractor which gives it the specific format you can see in the file.
Let me know if you have any questions,
Thanks you
Regards
Kadija

**Comment by ggalibert** [comment]
Not required anymore. The facility will be producing the NetcDF files themselves.
