### ISSUE TITLE
Reference to undefined IMOS.templates.dimensions.adcp_remapped

### ISSUE THREAD

**Issue by sspagnol** [aodn/imos-toolbox#773]
In Parser/OceanContour/OceanContour.m line 667 there is a code
```matlab
dimensions = IMOS.templates.dimensions.adcp_remapped;
```

but this does not exist in Util/+IMOS/+templates/dimensions.m, so not sure how oceanContourParser ever worked.

**Comment by lbesnard** [comment]
@sspagnol I found the same issue while trying to debug https://github.com/aodn/imos-toolbox/issues/775

I emailed @ocehugo to understand how this parser is meant to work.

At L440 (https://github.com/aodn/imos-toolbox/blob/master/Parser/OceanContour/OceanContour.m#L440 ), the following file should automatically be tested by the docstrings unittests written by hugo:

```
% file = [toolboxRootPath 'data/testfiles/netcdf/Nortek/OceanContour/Signature/s500_enu_avg.nc'];
```

However, running the toolbox with this file fails at L647 with the following error:

```
The class IMOS.templates.dimensions has no Constant property or Static method named 'adcp_remapped'.

Error in OceanContour.readOceanContourFile (line 647)
                dimensions = IMOS.templates.dimensions.adcp_remapped;
```

The only other reference is here:
https://github.com/aodn/imos-toolbox/blob/bf62109ec319cbe91993028f041a1a6ac9929122/Util/%2BIMOS/gen_dimensions.m#L9

**Comment by lbesnard** [comment]
fixed by https://github.com/aodn/imos-toolbox/pull/774
