### ISSUE TITLE
IMOS Bug Report: Nortek parsers are really slow

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aodn/imos-toolbox#92]
```
Each Nortek parser uses the readParadoppBinary function which generates a cell 
array of as many structures as sample data. This has for consequence that we 
need a for loop to read each structure and it slows Matlab considerably.
```

Original issue reported on code.google.com by `guillaum...@gmail.com` on 20 Jul 2011 at 1:27

**Comment by ggalibert** [comment]
Difficult to improve the parsers on this topic. In the meantime, since v2.5.24, a waitbar has been added so that the user knows that the toolbox is doing something when reading these files.
